
DROP TABLE Employees;

CREATE TABLE Employees(
                          id NUMBER  GENERATED BY DEFAULT ON NULL as IDENTITY,
                          salary NUMBER,
                          CONSTRAINT PK_ID PRIMARY KEY(id),
                          CONSTRAINT chk_salary CHECK(salary > 0)
);

DROP TABLE Departments;

CREATE TABLE Departments(
                            dept_id  NUMBER GENERATED BY DEFAULT ON NULL as IDENTITY
);


-- Disable a FOREIGN KEY constraint named fk_customer_order on the Orders table.

ALTER TABLE Orders DISABLE CONSTRAINT fk_customer_order;

-- ----------------------------------------------------------------------------------
-- Temporarily disable all constraints on the Products table.

DROP TABLE Products;

CREATE TABLE Products (
                          id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          name VARCHAR2(100),
                          price NUMBER,
                          category_id NUMBER,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (id),
                          CONSTRAINT UQ_PRODUCTS_NAME UNIQUE (name),
                          CONSTRAINT CH_PRICE CHECK (price > 0),
                          CONSTRAINT NN_PRODUCT_NAME CHECK (name IS NOT NULL)
);

-- Show all CONSTRAINTS in the table

SELECT constraint_name, constraint_type
FROM all_constraints
WHERE owner = 'ITEM'
  AND table_name = 'PRODUCTS';


-- Generate commands to disable all CONSTRAINTS
SELECT
    'ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT '
        || constraint_name || ';' AS disable_sql
FROM all_constraints
WHERE owner = 'ITEM'
  AND table_name = 'PRODUCTS';


ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT CH_PRICE;
ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT NN_PRODUCT_NAME;
ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT PK_PRODUCTS;
ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT UQ_PRODUCTS_NAME;

-- ----------------------------------------------------------------------------------
-- Write SQL to disable the CHECK constraint on the Accounts.balance column.

ALTER TABLE Accounts DISABLE CONSTRAINT CH_BALANCE;

-- ----------------------------------------------------------------------------------
-- Disable the PRIMARY KEY constraint on Departments(dept_id).

ALTER TABLE Departments DISABLE CONSTRAINT PK_DEPARMENTS;

-- ----------------------------------------------------------------------------------
-- How would you disable all constraints on a table before bulk inserting data?

-- Show all constraints on the Products table.
SELECT constraint_name, constraint_type
FROM all_constraints
WHERE owner = 'ITEM'
  AND table_name = 'PRODUCTS';

-- Generate SQL statements to disable all constraints.
SELECT
    'ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT '
        || constraint_name || ';' AS disable_sql
FROM all_constraints
WHERE owner = 'ITEM'
  AND table_name = 'PRODUCTS';

-- Execute the generated ALTER TABLE statements before performing the bulk insert.
ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT CH_PRICE;
ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT NN_PRODUCT_NAME;
ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT PK_PRODUCTS;
ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT UQ_PRODUCTS_NAME;

-- Note:
-- Another approach is to use a PL/SQL block with EXECUTE IMMEDIATE.
-- This method generates and executes the ALTER TABLE statements automatically,
-- so there is no need to copy and run the generated SQL manually.

BEGIN
FOR c IN (
        SELECT constraint_name
        FROM all_constraints
        WHERE owner = 'ITEM'
          AND table_name = 'PRODUCTS'
          AND constraint_name NOT LIKE 'SYS_%'
    ) LOOP
        EXECUTE IMMEDIATE
            'ALTER TABLE ITEM.PRODUCTS DISABLE CONSTRAINT ' || c.constraint_name;
END LOOP;
END;




