spring.application.name=Task1-Spring-Rest
server.port=8085

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb
spring.datasource.username=EWALLET
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf (dev: no cache)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Enable hidden _method (PUT/DELETE) from HTML forms
# HTML form only supports GET/POST, so we use:
# <input type="hidden" name="_method" value="PUT"/> or "DELETE"
spring.mvc.hiddenmethod.filter.enabled=true