
-- Create a table Employees with a CHECK constraint that ensures age is greater than or equal to 18.

CREATE TABLE Employees(
                          id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          age NUMBER CONSTRAINT NN_AGE NOT NULL,
                          CONSTRAINT PK_EMPLOYEES PRIMARY KEY(id),
                          CONSTRAINT CH_AGE CHECK(age >= 18)
);

-- SQL Error [2290] [23000]: ORA-02290: check constraint (ITEM.CH_AGE) violated
INSERT INTO EMPLOYEES (age) VALUES (10);

-- Updated Rows 1
INSERT INTO EMPLOYEES (age) VALUES (20);

SELECT * FROM Employees;

-- ----------------------------------------------------------------------------------------
-- Write a SQL query to enforce that salary in a Staff table must be between 3000 and 10000.


CREATE TABLE STAFF(
                      id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                      salary NUMBER CONSTRAINT NN_SALARY NOT NULL,
                      CONSTRAINT PK_STAFF PRIMARY KEY(id),
                      CONSTRAINT CH_SALARY CHECK(salary >= 3000 AND salary <= 10000)
);

-- SQL Error [2290] [23000]: ORA-02290: check constraint (ITEM.CH_SALARY) violated
INSERT INTO STAFF (salary) VALUES (2000);

-- Updated Rows 1
INSERT INTO STAFF (salary) VALUES (4000);

-- ----------------------------------------------------------------------------------------
-- Add a CHECK constraint to an existing table Products that ensures price is greater than 0.

ALTER TABLE Products
    ADD CONSTRAINT CH_PRICE CHECK(price > 0);

-- SQL Error [2290] [23000]: ORA-02290: check constraint (ITEM.CH_PRICE) violated
INSERT INTO Products (price) VALUES (-10);

-- Updated Rows 1
INSERT INTO Products (price) VALUES (1000);

-- ----------------------------------------------------------------------------------------
-- Create a table Students where the grade column only allows values from A to F using a CHECK constraint.

CREATE TABLE Students(
                         id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         grade CHAR CONSTRAINT NN_GRADE NOT NULL,
                         CONSTRAINT PK_STUDENTS PRIMARY KEY(id),
                         CONSTRAINT CH_GRADE CHECK(grade >= 'A' AND grade <= 'F')
);

-- SQL Error [2290] [23000]: ORA-02290: check constraint (ITEM.CH_GRADE) violated
INSERT INTO Students (grade) VALUES ('K');

-- SQL Error [2290] [23000]: ORA-02290: check constraint (ITEM.CH_GRADE) violated
INSERT INTO Students (grade) VALUES ('a');

-- Updated Rows 1
INSERT INTO Students (grade) VALUES ('A');

-- ----------------------------------------------------------------------------------------