-- List all departments and the employees working in them.
-- Use a RIGHT OUTER JOIN to ensure all departments are shown, even if they have no employees.

DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,   -- Remove NOT NULL

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);
-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (department_name, location)
VALUES ('IT', 'Cairo');

INSERT INTO Departments (department_name, location)
VALUES ('HR', 'Alexandria');

INSERT INTO Departments (department_name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (department_name, location)
VALUES ('Marketing', 'Assiut');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa', 18000, DATE '2024-01-15', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ahmed', 15000, DATE '2023-06-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara', 12000, DATE '2024-03-20', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona', 22000, DATE '2022-11-05', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar', 25000, DATE '2021-09-18', NULL);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Khaled', 13000, DATE '2026-07-20', NULL);

-------------------------------------------------
-- View data using RIGHT OUTER JOIN
-------------------------------------------------
SELECT e.employee_name,
       e.salary,
       e.hire_date,
       d.department_name,
       d.location
FROM Employees e
         RIGHT OUTER JOIN Departments d
                          ON e.department_id = d.department_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- Retrieve all orders and their corresponding customers.
--Use a RIGHT JOIN to include all customers, even if they haven't placed any orders.

DROP TABLE Orders;
DROP TABLE Customers;

-- Create Customers table
CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           city VARCHAR2(100),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-- Create Orders table
CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE,
                        total_amount NUMBER,
                        customer_id NUMBER,   -- Nullable (Some orders have no customer)

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),

                        CONSTRAINT FK_ORDER_CUSTOMER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id)
);

-------------------------------------------------
-- Insert sample customers
-------------------------------------------------

INSERT INTO Customers (customer_name, city)
VALUES ('Ali', 'Cairo');

INSERT INTO Customers (customer_name, city)
VALUES ('Sara', 'Alexandria');

INSERT INTO Customers (customer_name, city)
VALUES ('Mostafa', 'Giza');

INSERT INTO Customers (customer_name, city)
VALUES ('Mona', 'Assiut');

-------------------------------------------------
-- Insert sample orders
-------------------------------------------------

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-02', 1800, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-04', 1500, 4);

-- Orders without a matched customer
INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-05', 900, NULL);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-06', 1200, NULL);

-------------------------------------------------
-- View data using RIGHT OUTER JOIN
-------------------------------------------------

SELECT o.order_id, o.order_date, o.total_amount,
       c.customer_name
FROM Orders o
         RIGHT OUTER JOIN Customers c
                          ON o.customer_id = c.customer_id;


-- ---------------------------------------------------------------------------------------------------------------------
-- Show all courses and enrolled students.
-- Use RIGHT JOIN to return all courses, including those without any enrolled students.

DROP TABLE Students;
DROP TABLE Courses;

-- Create Courses table
CREATE TABLE Courses (
                         course_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         course_name VARCHAR2(100) NOT NULL,

                         CONSTRAINT PK_COURSES PRIMARY KEY (course_id)
);

-- Create Students table
CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          student_name VARCHAR2(100) NOT NULL,
                          age NUMBER,
                          course_id NUMBER,    -- Nullable (Some students are not enrolled in any course)

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id),

                          CONSTRAINT FK_STUDENT_COURSE
                              FOREIGN KEY (course_id)
                                  REFERENCES Courses(course_id)
);

-------------------------------------------------
-- Insert sample courses
-------------------------------------------------

INSERT INTO Courses (course_name)
VALUES ('Database Systems');

INSERT INTO Courses (course_name)
VALUES ('Data Structures');

INSERT INTO Courses (course_name)
VALUES ('Operating Systems');

INSERT INTO Courses (course_name)
VALUES ('Software Engineering');

-------------------------------------------------
-- Insert sample students
-------------------------------------------------

INSERT INTO Students (student_name, age, course_id)
VALUES ('Mostafa', 22, 1);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Ahmed', 21, 2);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Sara', 20, 3);

-- Students who are not enrolled in any course
INSERT INTO Students (student_name, age, course_id)
VALUES ('Omar', 24, NULL);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Hana', 21, NULL);

-------------------------------------------------
-- View data using RIGHT OUTER JOIN
-------------------------------------------------

SELECT s.student_name , c.course_name
FROM Students s
         RIGHT OUTER JOIN Courses c
                          ON s.course_id = c.course_id

-- ---------------------------------------------------------------------------------------------------------------------
-- Display all projects and the employees assigned to them.
-- Use a RIGHT OUTER JOIN to include all projects even if no employee is assigned.

DROP TABLE Employees;
DROP TABLE Projects;

-- Create Projects table
CREATE TABLE Projects (
                          project_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          project_name VARCHAR2(100) NOT NULL,
                          start_date DATE,

                          CONSTRAINT PK_PROJECTS PRIMARY KEY (project_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           project_id NUMBER,    -- Nullable (Some employees are not assigned to any project)

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_PROJECT
                               FOREIGN KEY (project_id)
                                   REFERENCES Projects(project_id)
);

-------------------------------------------------
-- Insert sample projects
-------------------------------------------------

INSERT INTO Projects (project_name, start_date)
VALUES ('Inventory System', DATE '2026-07-01');

INSERT INTO Projects (project_name, start_date)
VALUES ('E-Commerce Website', DATE '2026-07-05');

INSERT INTO Projects (project_name, start_date)
VALUES ('Hospital Management', DATE '2026-07-10');

INSERT INTO Projects (project_name, start_date)
VALUES ('HR System', DATE '2026-07-15');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Mostafa', 18000, 1);


INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Sara', 12000, 3);


-- Employees without a project
INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Ali', 14000, NULL);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Omar', 16000, NULL);

-------------------------------------------------
-- View data using RIGHT OUTER JOIN
-------------------------------------------------

SELECT e.employee_name, e.salary AS Employee_Salary,
       p.project_name, p.start_date
FROM Employees e
         RIGHT OUTER JOIN Projects p
                          ON e.project_id = p.project_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- Write a query to show all payment methods and their related transactions.
-- Include payment methods with no transactions using RIGHT JOIN.

DROP TABLE Transactions;
DROP TABLE Payment_Methods;

-- Create Payment_Methods table
CREATE TABLE Payment_Methods (
                                 payment_method_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                                 method_name VARCHAR2(100) NOT NULL,

                                 CONSTRAINT PK_PAYMENT_METHODS PRIMARY KEY (payment_method_id)
);

-- Create Transactions table
CREATE TABLE Transactions (
                              transaction_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                              transaction_date DATE,
                              amount NUMBER,
                              payment_method_id NUMBER,

                              CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (transaction_id),

                              CONSTRAINT FK_TRANSACTION_PAYMENT_METHOD
                                  FOREIGN KEY (payment_method_id)
                                      REFERENCES Payment_Methods(payment_method_id)
);

-------------------------------------------------
-- Insert sample payment methods
-------------------------------------------------

INSERT INTO Payment_Methods (method_name)
VALUES ('Cash');

INSERT INTO Payment_Methods (method_name)
VALUES ('Credit Card');

INSERT INTO Payment_Methods (method_name)
VALUES ('Debit Card');

INSERT INTO Payment_Methods (method_name)
VALUES ('Bank Transfer');

INSERT INTO Payment_Methods (method_name)
VALUES ('Mobile Wallet');

-------------------------------------------------
-- Insert sample transactions
-------------------------------------------------

INSERT INTO Transactions (transaction_date, amount, payment_method_id)
VALUES (DATE '2026-07-01', 500, 1);

INSERT INTO Transactions (transaction_date, amount, payment_method_id)
VALUES (DATE '2026-07-02', 1200, 2);

INSERT INTO Transactions (transaction_date, amount, payment_method_id)
VALUES (DATE '2026-07-03', 850, 2);

INSERT INTO Transactions (transaction_date, amount, payment_method_id)
VALUES (DATE '2026-07-04', 2000, 4);

-- Payment methods 3 (Debit Card) and 5 (Mobile Wallet)
-- have no related transactions.

-------------------------------------------------
-- View data using RIGHT OUTER JOIN
-------------------------------------------------

SELECT
    t.transaction_id,
    t.transaction_date,
    t.amount,
    p.method_name
FROM Transactions t
         RIGHT OUTER JOIN Payment_Methods p
                          ON t.payment_method_id = p.payment_method_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- Find all authors and their books.
-- Use a RIGHT OUTER JOIN to list all authors, even those who haven't written any books.

DROP TABLE Books;
DROP TABLE Authors;

-- Create Authors table
CREATE TABLE Authors (
                         author_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         author_name VARCHAR2(100) NOT NULL,
                         country VARCHAR2(50),

                         CONSTRAINT PK_AUTHORS PRIMARY KEY (author_id)
);

-- Create Books table
CREATE TABLE Books (
                       book_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       book_name VARCHAR2(100) NOT NULL,
                       price NUMBER,
                       author_id NUMBER,    -- Nullable (Some books have no assigned author)

                       CONSTRAINT PK_BOOKS PRIMARY KEY (book_id),

                       CONSTRAINT FK_BOOK_AUTHOR
                           FOREIGN KEY (author_id)
                               REFERENCES Authors(author_id)
);

-------------------------------------------------
-- Insert sample authors
-------------------------------------------------

INSERT INTO Authors (author_name, country)
VALUES ('Robert Martin', 'USA');

INSERT INTO Authors (author_name, country)
VALUES ('Thomas Cormen', 'USA');

INSERT INTO Authors (author_name, country)
VALUES ('Andrew Tanenbaum', 'Netherlands');

INSERT INTO Authors (author_name, country)
VALUES ('Martin Fowler', 'UK');

-------------------------------------------------
-- Insert sample books
-------------------------------------------------

INSERT INTO Books (book_name, price, author_id)
VALUES ('Clean Code', 50, 1);

INSERT INTO Books (book_name, price, author_id)
VALUES ('Refactoring', 70, 4);

-- Books without an assigned author
INSERT INTO Books (book_name, price, author_id)
VALUES ('Database Fundamentals', 45, 1);

INSERT INTO Books (book_name, price, author_id)
VALUES ('Cloud Computing Basics', 55, 4);

-------------------------------------------------
-- View data using RIGHT OUTER JOIN
-------------------------------------------------

SELECT b.book_name, a.author_name
FROM Books b
         RIGHT OUTER JOIN Authors a
                          ON b.author_id = a.author_id;


-- ---------------------------------------------------------------------------------------------------------------------
-- List all categories and the products under them.
--Use a RIGHT JOIN to ensure all categories are shown, even those with no products.

DROP TABLE Products;
DROP TABLE Categories;

-- Create Categories table
CREATE TABLE Categories (
                            category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            category_name VARCHAR2(100) NOT NULL,

                            CONSTRAINT PK_CATEGORIES PRIMARY KEY (category_id)
);

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          price NUMBER,
                          category_id NUMBER,    -- Nullable (Some products may not belong to any category)

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id),

                          CONSTRAINT FK_PRODUCT_CATEGORY
                              FOREIGN KEY (category_id)
                                  REFERENCES Categories(category_id)
);

-------------------------------------------------
-- Insert sample categories
-------------------------------------------------

INSERT INTO Categories (category_name)
VALUES ('Electronics');

INSERT INTO Categories (category_name)
VALUES ('Furniture');

INSERT INTO Categories (category_name)
VALUES ('Accessories');

INSERT INTO Categories (category_name)
VALUES ('Appliances');

-------------------------------------------------
-- Insert sample products
-------------------------------------------------

INSERT INTO Products (product_name, price, category_id)
VALUES ('Laptop', 25000, 1);

INSERT INTO Products (product_name, price, category_id)
VALUES ('Mouse', 500, 1);


-- Products without a category
INSERT INTO Products (product_name, price, category_id)
VALUES ('Mystery Item', 999, 3);

INSERT INTO Products (product_name, price, category_id)
VALUES ('Unknown Product', 1500, 3);

-------------------------------------------------
-- View data using RIGHT OUTER JOIN
-------------------------------------------------

SELECT
    p.product_name,
    p.price,
    c.category_name
FROM Products p
         RIGHT OUTER JOIN Categories c
                          ON p.category_id = c.category_id;


-- ---------------------------------------------------------------------------------------------------------------------
-- Retrieve all students and their assigned dorm rooms.
-- Use a RIGHT OUTER JOIN to include dorm rooms even if they are unassigned.

DROP TABLE Students;
DROP TABLE Dorm_Rooms;

-- Create Dorm_Rooms table
CREATE TABLE Dorm_Rooms (
                            room_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            room_number VARCHAR2(20) NOT NULL,
                            building VARCHAR2(100),

                            CONSTRAINT PK_DORM_ROOMS PRIMARY KEY (room_id)
);

-- Create Students table
CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          student_name VARCHAR2(100) NOT NULL,
                          age NUMBER,
                          room_id NUMBER,

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id),

                          CONSTRAINT FK_STUDENT_ROOM
                              FOREIGN KEY (room_id)
                                  REFERENCES Dorm_Rooms(room_id)
);

-------------------------------------------------
-- Insert sample dorm rooms
-------------------------------------------------

INSERT INTO Dorm_Rooms (room_number, building)
VALUES ('A101', 'Building A');

INSERT INTO Dorm_Rooms (room_number, building)
VALUES ('A102', 'Building A');

INSERT INTO Dorm_Rooms (room_number, building)
VALUES ('B201', 'Building B');

INSERT INTO Dorm_Rooms (room_number, building)
VALUES ('B202', 'Building B');

INSERT INTO Dorm_Rooms (room_number, building)
VALUES ('C301', 'Building C');

-------------------------------------------------
-- Insert sample students
-------------------------------------------------

INSERT INTO Students (student_name, age, room_id)
VALUES ('Mostafa', 22, 1);

INSERT INTO Students (student_name, age, room_id)
VALUES ('Ahmed', 21, 2);

INSERT INTO Students (student_name, age, room_id)
VALUES ('Sara', 20, 4);

-- Student without a room
INSERT INTO Students (student_name, age, room_id)
VALUES ('Mona', 23, NULL);

-------------------------------------------------
-- View data using RIGHT OUTER JOIN
-------------------------------------------------

SELECT
    s.student_name,
    s.age,
    d.room_number,
    d.building
FROM Students s
         RIGHT OUTER JOIN Dorm_Rooms d
                          ON s.room_id = d.room_id;