-- Find the names of employees who earn more than the average salary.
-- Use a subquery to calculate the average salary.

DROP TABLE Employees;

CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id)
);
-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary)
VALUES ('Mostafa', 18000);

INSERT INTO Employees (employee_name, salary)
VALUES ('Ahmed', 15000);

INSERT INTO Employees (employee_name, salary)
VALUES ('Sara', NULL);

INSERT INTO Employees (employee_name, salary)
VALUES ('Mona', 22000);

INSERT INTO Employees (employee_name, salary)
VALUES ('Ali', NULL);

INSERT INTO Employees (employee_name, salary)
VALUES ('Omar', 17500);

INSERT INTO Employees (employee_name, salary)
VALUES ('Hana', NULL);

INSERT INTO Employees (employee_name, salary)
VALUES ('Youssef', 13000);


SELECT employee_name, salary
FROM Employees WHERE salary > ((SELECT sum(salary) FROM Employees) / (SELECT count(salary) FROM Employees));

-- another solution
SELECT employee_name, salary
FROM Employees WHERE salary > (SELECT avg(salary) FROM Employees);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- List the customers who placed the highest number of orders.
-- Use a subquery to count orders per customer and compare with the max count.

DROP TABLE Orders;
DROP TABLE Customers;

-- Create Customers table
CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           email VARCHAR2(100),
                           city VARCHAR2(50),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-- Create Orders table
CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE,
                        total_amount NUMBER,
                        customer_id NUMBER NOT NULL,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),

                        CONSTRAINT FK_ORDER_CUSTOMER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id)
);

-------------------------------------------------
-- Insert sample customers
-------------------------------------------------

INSERT INTO Customers (customer_name, email, city)
VALUES ('Mostafa Talat', 'mostafa@gmail.com', 'Cairo');

INSERT INTO Customers (customer_name, email, city)
VALUES ('Ahmed Mohamed', 'ahmed@gmail.com', 'Alexandria');

INSERT INTO Customers (customer_name, email, city)
VALUES ('Sara Ali', 'sara@gmail.com', 'Giza');

INSERT INTO Customers (customer_name, email, city)
VALUES ('Mona Hassan', 'mona@gmail.com', 'Assiut');

INSERT INTO Customers (customer_name, email, city)
VALUES ('Omar Khaled', 'omar@gmail.com', 'Luxor');

-------------------------------------------------
-- Insert sample orders
-------------------------------------------------

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-01', 1200, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-03', 850, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-04', 2300, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-05', 500, 3);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-07', 1750, 4);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-08', 900, 5);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-10', 650, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-11', 1450, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-12', 3200, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-13', 700, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-14', 980, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-15', 2750, 3);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-16', 1800, 3);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-17', 450, 4);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-18', 3900, 4);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-19', 1100, 5);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-20', 2600, 5);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-21', 1500, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-22', 600, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-23', 4200, 3);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-24', 850, 4);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-25', 1300, 5);

SELECT *
FROM Customers c
WHERE (
          SELECT COUNT(*)
          FROM Orders o
          WHERE c.customer_id = o.customer_id
      ) = (
          SELECT MAX(COUNT(*))
          FROM Orders
          GROUP BY customer_id
      );


-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Retrieve all products whose price is higher than any product in the ‘Accessories’ category.
-- Use a subquery inside a WHERE clause with ANY.


DROP TABLE Products;

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          category VARCHAR2(100) NOT NULL,
                          price NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-------------------------------------------------
-- Insert sample data
-------------------------------------------------

INSERT INTO Products (product_name, category, price)
VALUES ('Laptop', 'Electronics', 25000);

INSERT INTO Products (product_name, category, price)
VALUES ('Monitor', 'Electronics', 7000);

INSERT INTO Products (product_name, category, price)
VALUES ('Mouse', 'Accessories', 250);

INSERT INTO Products (product_name, category, price)
VALUES ('Keyboard', 'Accessories', 600);

INSERT INTO Products (product_name, category, price)
VALUES ('Headphones', 'Accessories', 1200);

INSERT INTO Products (product_name, category, price)
VALUES ('USB Flash Drive', 'Accessories', 350);

INSERT INTO Products (product_name, category, price)
VALUES ('Office Chair', 'Furniture', 4500);

INSERT INTO Products (product_name, category, price)
VALUES ('Desk', 'Furniture', 5500);

INSERT INTO Products (product_name, category, price)
VALUES ('Printer', 'Office', 3800);

INSERT INTO Products (product_name, category, price)
VALUES ('Scanner', 'Office', 3200);


SELECT *
FROM Products
WHERE price > ANY(
    SELECT price
    FROM Products
    WHERE category = 'Accessories'
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Display employees who work in the same department as 'John Smith'.
-- Use a subquery to get John Smith’s department ID.

DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (department_name, location)
VALUES ('Human Resources', 'Cairo');

INSERT INTO Departments (department_name, location)
VALUES ('IT', 'Alexandria');

INSERT INTO Departments (department_name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (department_name, location)
VALUES ('Sales', 'Assiut');

INSERT INTO Departments (department_name, location)
VALUES ('Marketing', 'Luxor');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('John Smith', 18000, DATE '2022-01-15', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ahmed Mohamed', 15000, DATE '2021-03-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara Ali', 17000, DATE '2020-07-18', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali Mahmoud', 16000, DATE '2022-09-30', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Hana Samir', 15500, DATE '2023-08-14', 3);


SELECT *
FROM Employees
WHERE department_id = (
    SELECT department_id
    FROM Employees
    WHERE employee_name = 'John Smith'
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Get all orders that were placed by customers from 'New York'.
-- Use a subquery to filter customers based on city.

DROP TABLE Orders;
DROP TABLE Customers;

-- Create Customers table
CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           city VARCHAR2(100) NOT NULL,
                           phone VARCHAR2(20),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-- Create Orders table
CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE NOT NULL,
                        total_amount NUMBER NOT NULL,
                        customer_id NUMBER NOT NULL,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),

                        CONSTRAINT FK_ORDER_CUSTOMER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id)
);

-------------------------------------------------
-- Insert sample customers
-------------------------------------------------

INSERT INTO Customers (customer_name, city, phone)
VALUES ('John Smith', 'New York', '01012345678');

INSERT INTO Customers (customer_name, city, phone)
VALUES ('Ahmed Mohamed', 'Cairo', '01123456789');

INSERT INTO Customers (customer_name, city, phone)
VALUES ('Sara Ali', 'Alexandria', '01234567890');

INSERT INTO Customers (customer_name, city, phone)
VALUES ('Mostafa Talat', 'Cairo', '01512345678');

INSERT INTO Customers (customer_name, city, phone)
VALUES ('Mona Hassan', 'New York', '01098765432');

INSERT INTO Customers (customer_name, city, phone)
VALUES ('Ali Mahmoud', 'Alexandria', '01187654321');

INSERT INTO Customers (customer_name, city, phone)
VALUES ('Omar Khaled', 'Luxor', '01211223344');

INSERT INTO Customers (customer_name, city, phone)
VALUES ('Hana Samir', 'Aswan', '01555667788');

-------------------------------------------------
-- Insert sample orders
-------------------------------------------------

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-01', 1200, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-02', 850, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-03', 2300, 3);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-04', 1750, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-05', 950, 4);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-06', 3000, 5);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-07', 450, 6);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-08', 2200, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-09', 600, 7);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-10', 1800, 8);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-11', 750, 4);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-12', 2600, 3);

SELECT *
FROM orders
WHERE customer_id IN (
    SELECT customer_id
    FROM Customers
    WHERE city = 'New York'
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Find the departments that have no employees.
-- Use a NOT EXISTS subquery to check for departments without employees.


DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (department_name, location)
VALUES ('Human Resources', 'Cairo');

INSERT INTO Departments (department_name, location)
VALUES ('IT', 'Alexandria');

INSERT INTO Departments (department_name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (department_name, location)
VALUES ('Sales', 'Assiut');

INSERT INTO Departments (department_name, location)
VALUES ('Marketing', 'Luxor');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('John Smith', 18000, DATE '2022-01-15', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ahmed Mohamed', 15000, DATE '2021-03-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara Ali', 17000, DATE '2020-07-18', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali Mahmoud', 16000, DATE '2022-09-30', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Hana Samir', 15500, DATE '2023-08-14', 3);


SELECT *
FROM Departments d
WHERE NOT EXISTS (
    SELECT 1
    FROM Employees e
    WHERE d.department_id = e.department_id
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- List the students who are not enrolled in any course.
-- Use a subquery with NOT IN or NOT EXISTS.


DROP TABLE Students;
DROP TABLE Courses;

-- Create Courses table
CREATE TABLE Courses (
                         course_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         course_name VARCHAR2(100) NOT NULL,

                         CONSTRAINT PK_COURSES PRIMARY KEY (course_id)
);

-- Create Students table
CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          student_name VARCHAR2(100) NOT NULL,
                          age NUMBER,
                          course_id NUMBER,    -- Nullable (Some students are not enrolled in any course)

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id),

                          CONSTRAINT FK_STUDENT_COURSE
                              FOREIGN KEY (course_id)
                                  REFERENCES Courses(course_id)
);

-------------------------------------------------
-- Insert sample courses
-------------------------------------------------

INSERT INTO Courses (course_name)
VALUES ('Database Systems');

INSERT INTO Courses (course_name)
VALUES ('Data Structures');

INSERT INTO Courses (course_name)
VALUES ('Operating Systems');

INSERT INTO Courses (course_name)
VALUES ('Software Engineering');

-------------------------------------------------
-- Insert sample students
-------------------------------------------------

INSERT INTO Students (student_name, age, course_id)
VALUES ('Mostafa', 22, 1);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Ahmed', 21, 2);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Sara', 20, 3);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Omar', 24, NULL);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Hana', 21, NULL);


-- USING  NOT EXISTS

SELECT *
FROM Students s
WHERE NOT EXISTS (
    SELECT 1
    FROM Courses c
    WHERE s.course_id = c.course_id
);


-- USING NOT IN

SELECT *
FROM Students s
WHERE s.course_id NOT IN (
    SELECT c.course_id
    FROM Courses c
    WHERE s.course_id = c.course_id
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Retrieve the second highest salary from the employees table.
-- Use a subquery with MAX and WHERE.

DROP TABLE Employees;

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id)
);


INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('John Smith', 18000, DATE '2022-01-15');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Ahmed Mohamed', 15000, DATE '2021-03-10');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Sara Ali', 17000, DATE '2020-07-18');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Ali Mahmoud', 16000, DATE '2022-09-30');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('aboda', 18000, DATE '2022-09-30');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Hana Samir', 15500, DATE '2023-08-14');

SELECT *
FROM  Employees e
WHERE salary = (
    SELECT max(salary)
    FROM Employees
    WHERE salary !=(
    SELECT max(salary)
    FROM Employees
    )
    );


-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Display products that have a price greater than the average price of all products.
-- Use a scalar subquery to get the average price.


DROP TABLE Products;

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          category VARCHAR2(100) NOT NULL,
                          price NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-------------------------------------------------
-- Insert sample data
-------------------------------------------------

INSERT INTO Products (product_name, category, price)
VALUES ('Laptop', 'Electronics', 25000);

INSERT INTO Products (product_name, category, price)
VALUES ('Monitor', 'Electronics', 7000);

INSERT INTO Products (product_name, category, price)
VALUES ('Mouse', 'Accessories', 250);

INSERT INTO Products (product_name, category, price)
VALUES ('Keyboard', 'Accessories', 600);

INSERT INTO Products (product_name, category, price)
VALUES ('Headphones', 'Accessories', 1200);

INSERT INTO Products (product_name, category, price)
VALUES ('USB Flash Drive', 'Accessories', 350);

INSERT INTO Products (product_name, category, price)
VALUES ('Office Chair', 'Furniture', 4500);

INSERT INTO Products (product_name, category, price)
VALUES ('Desk', 'Furniture', 5500);

INSERT INTO Products (product_name, category, price)
VALUES ('Printer', 'Office', 3800);

INSERT INTO Products (product_name, category, price)
VALUES ('Scanner', 'Office', 3200);


SELECT *
FROM Products
WHERE price > (
    SELECT avg(price)
    FROM Products
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Find customers who have ordered all products in category 'A'.
-- Use a correlated subquery with NOT EXISTS.

DROP TABLE Orders;
DROP TABLE Products;
DROP TABLE Customers;

-------------------------------------------------
-- Create Customers table
-------------------------------------------------

CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           city VARCHAR2(100),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-------------------------------------------------
-- Create Products table
-------------------------------------------------

CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          category CHAR(1) NOT NULL,
                          price NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-------------------------------------------------
-- Create Orders table
-------------------------------------------------

CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE NOT NULL,
                        quantity NUMBER NOT NULL,
                        customer_id NUMBER NOT NULL,
                        product_id NUMBER NOT NULL,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),

                        CONSTRAINT FK_ORDER_CUSTOMER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id),

                        CONSTRAINT FK_ORDER_PRODUCT
                            FOREIGN KEY (product_id)
                                REFERENCES Products(product_id)
);

-------------------------------------------------
-- Insert sample customers
-------------------------------------------------

INSERT INTO Customers (customer_name, city)
VALUES ('John Smith', 'New York');

INSERT INTO Customers (customer_name, city)
VALUES ('Mostafa Talat', 'Cairo');

INSERT INTO Customers (customer_name, city)
VALUES ('Ahmed Mohamed', 'Alexandria');

INSERT INTO Customers (customer_name, city)
VALUES ('Sara Ali', 'Giza');

INSERT INTO Customers (customer_name, city)
VALUES ('Mona Hassan', 'Luxor');

INSERT INTO Customers (customer_name, city)
VALUES ('Ali Mahmoud', 'Assiut');

INSERT INTO Customers (customer_name, city)
VALUES ('Omar Khaled', 'Aswan');

INSERT INTO Customers (customer_name, city)
VALUES ('Hana Samir', 'Tanta');

-------------------------------------------------
-- Insert sample products
-------------------------------------------------

INSERT INTO Products (product_name, category, price)
VALUES ('Laptop', 'A', 25000);

INSERT INTO Products (product_name, category, price)
VALUES ('Mouse', 'A', 500);

INSERT INTO Products (product_name, category, price)
VALUES ('Keyboard', 'A', 700);

INSERT INTO Products (product_name, category, price)
VALUES ('Monitor', 'B', 6500);

INSERT INTO Products (product_name, category, price)
VALUES ('Printer', 'B', 4200);

INSERT INTO Products (product_name, category, price)
VALUES ('Desk', 'C', 5500);

INSERT INTO Products (product_name, category, price)
VALUES ('Office Chair', 'C', 3200);

INSERT INTO Products (product_name, category, price)
VALUES ('Scanner', 'B', 2800);

-------------------------------------------------
-- Insert sample orders
-------------------------------------------------

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-01', 1, 1, 1);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-02', 2, 1, 2);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-03', 1, 1, 3);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-04', 3, 4, 4);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-05', 2, 5, 5);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-06', 1, 6, 6);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-07', 4, 7, 1);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-08', 2, 8, 7);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-09', 1, 1, 8);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-10', 5, 2, 3);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-11', 2, 3, 2);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-12', 1, 4, 5);


SELECT *
FROM Customers c
WHERE NOT EXISTS (
    SELECT *
    FROM Products p
    WHERE p.category = 'A'
      AND NOT EXISTS (
        SELECT *
        FROM Orders o
        WHERE o.customer_id = c.customer_id
          AND o.product_id = p.product_id
    )
);
