-- Find the employee(s) with the highest salary.
--Use a single-row subquery to get the maximum salary.

DROP TABLE Employees;

CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id)
);
-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary)
VALUES ('Mostafa', 18000);

INSERT INTO Employees (employee_name, salary)
VALUES ('Ahmed', 15000);

INSERT INTO Employees (employee_name, salary)
VALUES ('Sara', NULL);

INSERT INTO Employees (employee_name, salary)
VALUES ('Mona', 22000);

INSERT INTO Employees (employee_name, salary)
VALUES ('Ali', NULL);

INSERT INTO Employees (employee_name, salary)
VALUES ('Omar', 17500);

INSERT INTO Employees (employee_name, salary)
VALUES ('Hana', NULL);

INSERT INTO Employees (employee_name, salary)
VALUES ('Youssef', 13000);

INSERT INTO Employees (employee_name, salary)
VALUES ('Amer', 22000);

INSERT INTO Employees (employee_name, salary)
VALUES ('Ammar', 22000);


SELECT *
FROM Employees WHERE salary = ((SELECT max(salary) FROM Employees));

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- List the names of employees who work in the same department as employee 'Alice'.
-- Use a subquery to get the department ID of 'Alice'.
DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (department_name, location)
VALUES ('Human Resources', 'Cairo');

INSERT INTO Departments (department_name, location)
VALUES ('IT', 'Alexandria');

INSERT INTO Departments (department_name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (department_name, location)
VALUES ('Sales', 'Assiut');

INSERT INTO Departments (department_name, location)
VALUES ('Marketing', 'Luxor');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('John Smith', 18000, DATE '2022-01-15', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Alice', 15000, DATE '2021-03-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara Ali', 17000, DATE '2020-07-18', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali Mahmoud', 16000, DATE '2022-09-30', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Hana Samir', 15500, DATE '2023-08-14', 3);


SELECT *
FROM Employees
WHERE department_id = (
    SELECT department_id
    FROM Employees
    WHERE employee_name = 'Alice'
);



-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Display the details of the product with the lowest price.
-- Use a single-row subquery to get the minimum price.


DROP TABLE Products;

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          category VARCHAR2(100) NOT NULL,
                          price NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-------------------------------------------------
-- Insert sample data
-------------------------------------------------

INSERT INTO Products (product_name, category, price)
VALUES ('Laptop', 'Electronics', 25000);

INSERT INTO Products (product_name, category, price)
VALUES ('Monitor', 'Electronics', 7000);

INSERT INTO Products (product_name, category, price)
VALUES ('Mouse', 'Accessories', 350);

INSERT INTO Products (product_name, category, price)
VALUES ('Keyboard', 'Accessories', 350);

INSERT INTO Products (product_name, category, price)
VALUES ('Headphones', 'Accessories', 1200);

INSERT INTO Products (product_name, category, price)
VALUES ('USB Flash Drive', 'Accessories', 350);

INSERT INTO Products (product_name, category, price)
VALUES ('Office Chair', 'Furniture', 4500);

INSERT INTO Products (product_name, category, price)
VALUES ('Desk', 'Furniture', 5500);

INSERT INTO Products (product_name, category, price)
VALUES ('Printer', 'Office', 3800);

INSERT INTO Products (product_name, category, price)
VALUES ('Scanner', 'Office', 3200);


SELECT *
FROM Products
WHERE price = (
    SELECT min(price)
    FROM Products
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Retrieve the department name of the employee with the highest salary.
-- Use nested subqueries: one to find the employee, and one to find the department.

DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (department_name, location)
VALUES ('Human Resources', 'Cairo');

INSERT INTO Departments (department_name, location)
VALUES ('IT', 'Alexandria');

INSERT INTO Departments (department_name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (department_name, location)
VALUES ('Sales', 'Assiut');

INSERT INTO Departments (department_name, location)
VALUES ('Marketing', 'Luxor');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('John Smith', 18000, DATE '2022-01-15', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ahmed Mohamed', 15000, DATE '2021-03-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara Ali', 17000, DATE '2020-07-18', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali Mahmoud', 16000, DATE '2022-09-30', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Hana Samir', 15500, DATE '2023-08-14', 3);


SELECT *
FROM Departments d
WHERE d.department_id = (
    SELECT e.department_id
    FROM Employees e
    WHERE e.salary = (
        SELECT max(e1.salary)
        FROM Employees e1
    )
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Find the manager of the employee who was hired most recently.
-- Use a subquery to get the employee with the latest hire date.
DROP TABLE Employees;
DROP TABLE Managers;

-------------------------------------------------
-- Create Managers table
-------------------------------------------------

CREATE TABLE Managers (
                          manager_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          manager_name VARCHAR2(100) NOT NULL,
                          department VARCHAR2(100),

                          CONSTRAINT PK_MANAGERS PRIMARY KEY (manager_id)
);

-------------------------------------------------
-- Create Employees table
-------------------------------------------------

CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           manager_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_MANAGER
                               FOREIGN KEY (manager_id)
                                   REFERENCES Managers(manager_id)
);

-------------------------------------------------
-- Insert sample managers
-------------------------------------------------

INSERT INTO Managers (manager_name, department)
VALUES ('John Smith', 'IT');

INSERT INTO Managers (manager_name, department)
VALUES ('Ahmed Hassan', 'Finance');

INSERT INTO Managers (manager_name, department)
VALUES ('Sara Ali', 'Human Resources');

INSERT INTO Managers (manager_name, department)
VALUES ('Mona Ibrahim', 'Sales');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, manager_id)
VALUES ('Mostafa Talat', 18000, DATE '2023-01-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, manager_id)
VALUES ('Ali Mahmoud', 15000, DATE '2022-06-15', 1);

INSERT INTO Employees (employee_name, salary, hire_date, manager_id)
VALUES ('Omar Khaled', 17000, DATE '2021-09-20', 2);

INSERT INTO Employees (employee_name, salary, hire_date, manager_id)
VALUES ('Hana Samir', 16000, DATE '2024-02-05', 2);

INSERT INTO Employees (employee_name, salary, hire_date, manager_id)
VALUES ('Mona Hassan', 14500, DATE '2023-08-18', 3);

INSERT INTO Employees (employee_name, salary, hire_date, manager_id)
VALUES ('Youssef Adel', 15500, DATE '2022-11-30', 4);

INSERT INTO Employees (employee_name, salary, hire_date, manager_id)
VALUES ('Nada Mohamed', 14000, DATE '2024-03-12', 4);


SELECT *
FROM Managers m
WHERE m.manager_id = (
    SELECT e.manager_id
    FROM Employees e
    WHERE e.hire_date =(
        SELECT MAX(e1.hire_date)
        FROM Employees e1
    )
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Show the employee whose salary is equal to the average salary of the company.
-- Use a single-row subquery with AVG().

DROP TABLE Employees;

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id)
);

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('John Smith', 10000, DATE '2022-01-15');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Ahmed Mohamed', 15000, DATE '2021-03-10');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Sara Ali', 20000, DATE '2020-07-18');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Mostafa Talat', 15000, DATE '2023-11-25');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Mona Hassan', 12000, DATE '2024-05-12');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Ali Mahmoud', 18000, DATE '2022-09-30');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Omar Khaled', NULL, DATE '2024-02-20');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Hana Samir', 15000, DATE '2023-08-14');


SELECT *
FROM Employees
WHERE salary = (
    SELECT avg(salary)
    FROM Employees
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- List the order(s) with the earliest order date.
-- Use a subquery to get the minimum order date.

DROP TABLE Orders;

-------------------------------------------------
-- Create Orders table
-------------------------------------------------

CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE NOT NULL,
                        quantity NUMBER NOT NULL,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id)
);

-------------------------------------------
-- Insert sample orders
-------------------------------------------------

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-01', 1);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-02', 2);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-03', 1);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-04', 3);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-05', 2);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-06', 1);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-07', 4);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-08', 2);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-09', 1);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-10', 5);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-11', 2);

INSERT INTO Orders (order_date, quantity)
VALUES (DATE '2026-07-12', 1);

SELECT *
FROM Orders
WHERE order_date = (
    SELECT max(ORDER_DATE)
    FROM Orders
);


-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Get the name and salary of the employee who earns more than the employee with ID = 101.
-- Use a single-row subquery to get the salary of employee 101.

DROP TABLE Employees;

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id)
);


INSERT INTO Employees (employee_id,employee_name, salary, hire_date)
VALUES (101, 'John Smith', 18000, DATE '2022-01-15');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Ahmed Mohamed', 15000, DATE '2021-03-10');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Sara Ali', 17000, DATE '2020-07-18');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Ali Mahmoud', 16000, DATE '2022-09-30');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('aboda', 18000, DATE '2022-09-30');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20');

INSERT INTO Employees (employee_name, salary, hire_date)
VALUES ('Hana Samir', 15500, DATE '2023-08-14');

SELECT *
FROM  Employees e
WHERE e.salary > (
    SELECT salary
    FROM Employees e1
    WHERE e1.employee_id = 101
);


-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Find the student who has the same GPA as student 'John Doe'.
-- Use a subquery to get 'John Doe’s GPA'.

DROP TABLE Students;

-------------------------------------------------
-- Create Students table
-------------------------------------------------

CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          student_name VARCHAR2(100) NOT NULL,
                          gpa NUMBER(3,2),
                          major VARCHAR2(100),

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id),

                          CONSTRAINT CHK_STUDENT_GPA
                              CHECK (gpa BETWEEN 0.00 AND 4.00)
);

-------------------------------------------------
-- Insert sample students
-------------------------------------------------

INSERT INTO Students (student_name, gpa, major)
VALUES ('John Smith', 3.85, 'Computer Science');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Ahmed Mohamed', 3.20, 'Information Systems');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Sara Ali', 3.95, 'Computer Science');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Mostafa Talat', 3.60, 'Software Engineering');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Mona Hassan', 2.90, 'Business Administration');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Ali Mahmoud', 3.40, 'Artificial Intelligence');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Omar Khaled', 3.85, 'Cyber Security');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Hana Samir', 4.00, 'Data Science');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Youssef Adel', 1.90, 'Computer Engineering');

INSERT INTO Students (student_name, gpa, major)
VALUES ('Nada Ibrahim', 3.10, 'Software Engineering');

SELECT *
FROM Students s
WHERE s.gpa = (
    SELECT s1.gpa
    FROM Students s1
    WHERE s1.student_name = 'John Smith'
);


-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Display all books that have the same price as the most expensive book in the ‘Science’ category.
-- Use a subquery to find the max price from the 'Science' category.


DROP TABLE Books;


-- Create Books table
CREATE TABLE Books (
                       book_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       book_name VARCHAR2(100) NOT NULL,
                       price NUMBER,
                       category VARCHAR2(100),

                       CONSTRAINT PK_BOOKS PRIMARY KEY (book_id)
);

-------------------------------------------------
-- Insert sample books
-------------------------------------------------

INSERT INTO Books (book_name, price, category)
VALUES ('Physics Fundamentals', 650, 'Science');

INSERT INTO Books (book_name, price, category)
VALUES ('Introduction to Chemistry', 520, 'Science');

INSERT INTO Books (book_name, price, category)
VALUES ('Biology Essentials', 480, 'Science');

INSERT INTO Books (book_name, price, category)
VALUES ('Astronomy Basics', 600, 'Science');

INSERT INTO Books (book_name, price, category)
VALUES ('Environmental Science', 550, 'Science');

INSERT INTO Books (book_name, price, category)
VALUES ('World History', 400, 'History');

INSERT INTO Books (book_name, price, category)
VALUES ('Modern Literature', 350, 'Literature');

INSERT INTO Books (book_name, price, category)
VALUES ('Business Management', 700, 'Business');

INSERT INTO Books (book_name, price, category)
VALUES ('Database Systems', 650, 'Technology');

INSERT INTO Books (book_name, price, category)
VALUES ('Artificial Intelligence', 900, 'Technology');

SELECT *
FROM Books
WHERE category != 'Science'
AND price = (
	SELECT max(price)
	FROM Books
	WHERE category = 'Science'
);