-- Retrieve all employees and their department names.
-- Write an Oracle SQL query using LEFT OUTER JOIN to show all employees, including those who are not assigned to any department.


DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,   -- Remove NOT NULL

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);
-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (department_name, location)
VALUES ('IT', 'Cairo');

INSERT INTO Departments (department_name, location)
VALUES ('HR', 'Alexandria');

INSERT INTO Departments (department_name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (department_name, location)
VALUES ('Marketing', 'Assiut');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa', 18000, DATE '2024-01-15', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ahmed', 15000, DATE '2023-06-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara', 12000, DATE '2024-03-20', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona', 22000, DATE '2022-11-05', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali', 14000, DATE '2025-02-01', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar', 25000, DATE '2021-09-18', NULL);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Khaled', 13000, DATE '2026-07-20', NULL);

-------------------------------------------------
-- View data
-------------------------------------------------

SELECT
    e.employee_name,
    e.salary,
    e.hire_date,
    d.department_name,
    d.location
FROM Employees e
         LEFT OUTER JOIN Departments d
                         ON e.department_id = d.department_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- List all products and their associated categories.
-- Some products may not belong to any category. Write a query using LEFT JOIN to include all products regardless of category association.
DROP TABLE Products;
DROP TABLE Categories;

-- Create Categories table
CREATE TABLE Categories (
                            category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            category_name VARCHAR2(100) NOT NULL,

                            CONSTRAINT PK_CATEGORIES PRIMARY KEY (category_id)
);

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          price NUMBER,
                          category_id NUMBER,    -- Nullable (Some products may not belong to any category)

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id),

                          CONSTRAINT FK_PRODUCT_CATEGORY
                              FOREIGN KEY (category_id)
                                  REFERENCES Categories(category_id)
);

-------------------------------------------------
-- Insert sample categories
-------------------------------------------------

INSERT INTO Categories (category_name)
VALUES ('Electronics');

INSERT INTO Categories (category_name)
VALUES ('Furniture');

INSERT INTO Categories (category_name)
VALUES ('Accessories');

INSERT INTO Categories (category_name)
VALUES ('Appliances');

-------------------------------------------------
-- Insert sample products
-------------------------------------------------

INSERT INTO Products (product_name, price, category_id)
VALUES ('Laptop', 25000, 1);

INSERT INTO Products (product_name, price, category_id)
VALUES ('Mouse', 500, 1);

INSERT INTO Products (product_name, price, category_id)
VALUES ('Office Chair', 3500, 2);

INSERT INTO Products (product_name, price, category_id)
VALUES ('USB Flash', 350, 3);

INSERT INTO Products (product_name, price, category_id)
VALUES ('Headphones', 1800, 3);

-- Products without a category
INSERT INTO Products (product_name, price, category_id)
VALUES ('Mystery Item', 999, NULL);

INSERT INTO Products (product_name, price, category_id)
VALUES ('Unknown Product', 1500, NULL);

-------------------------------------------------
-- View data using LEFT OUTER JOIN
-------------------------------------------------

SELECT
    p.product_name,
    p.price,
    c.category_name
FROM Products p
         LEFT OUTER JOIN Categories c
                         ON p.category_id = c.category_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- Find all students and the courses they are enrolled in.
-- Use a LEFT OUTER JOIN to include students who are not enrolled in any course.

DROP TABLE Students;
DROP TABLE Courses;

-- Create Courses table
CREATE TABLE Courses (
                         course_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         course_name VARCHAR2(100) NOT NULL,

                         CONSTRAINT PK_COURSES PRIMARY KEY (course_id)
);

-- Create Students table
CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          student_name VARCHAR2(100) NOT NULL,
                          age NUMBER,
                          course_id NUMBER,    -- Nullable (Some students are not enrolled in any course)

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id),

                          CONSTRAINT FK_STUDENT_COURSE
                              FOREIGN KEY (course_id)
                                  REFERENCES Courses(course_id)
);

-------------------------------------------------
-- Insert sample courses
-------------------------------------------------

INSERT INTO Courses (course_name)
VALUES ('Database Systems');

INSERT INTO Courses (course_name)
VALUES ('Data Structures');

INSERT INTO Courses (course_name)
VALUES ('Operating Systems');

INSERT INTO Courses (course_name)
VALUES ('Software Engineering');

-------------------------------------------------
-- Insert sample students
-------------------------------------------------

INSERT INTO Students (student_name, age, course_id)
VALUES ('Mostafa', 22, 1);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Ahmed', 21, 2);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Sara', 20, 3);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Ali', 23, 4);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Mona', 22, 1);

-- Students who are not enrolled in any course
INSERT INTO Students (student_name, age, course_id)
VALUES ('Omar', 24, NULL);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Hana', 21, NULL);

-------------------------------------------------
-- View data using LEFT OUTER JOIN
-------------------------------------------------

SELECT s.student_name , c.course_name
FROM Students s
         LEFT OUTER JOIN Courses c
                         ON s.course_id = c.course_id

-- ---------------------------------------------------------------------------------------------------------------------
-- Display all orders with customer names, including orders without a matched customer.
-- Assume the orders table has a foreign key customer_id. Use LEFT JOIN to include all orders.

DROP TABLE Orders;
DROP TABLE Customers;

-- Create Customers table
CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           city VARCHAR2(100),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-- Create Orders table
CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE,
                        total_amount NUMBER,
                        customer_id NUMBER,   -- Nullable (Some orders have no customer)

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),

                        CONSTRAINT FK_ORDER_CUSTOMER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id)
);

-------------------------------------------------
-- Insert sample customers
-------------------------------------------------

INSERT INTO Customers (customer_name, city)
VALUES ('Ali', 'Cairo');

INSERT INTO Customers (customer_name, city)
VALUES ('Sara', 'Alexandria');

INSERT INTO Customers (customer_name, city)
VALUES ('Mostafa', 'Giza');

INSERT INTO Customers (customer_name, city)
VALUES ('Mona', 'Assiut');

-------------------------------------------------
-- Insert sample orders
-------------------------------------------------

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-01', 2500, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-02', 1800, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-03', 3200, 3);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-04', 1500, 4);

-- Orders without a matched customer
INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-05', 900, NULL);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-06', 1200, NULL);

-------------------------------------------------
-- View data using LEFT OUTER JOIN
-------------------------------------------------

SELECT o.order_id, o.order_date, o.total_amount,
       c.customer_name
FROM Orders o
         LEFT OUTER JOIN Customers c
                         ON o.customer_id = c.customer_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- Show all departments and their managers.
-- Write a query to return all departments using a LEFT OUTER JOIN to show their assigned managers, including departments with no manager.

DROP TABLE Departments;
DROP TABLE Managers;

-- Create Managers table
CREATE TABLE Managers (
                          manager_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          manager_name VARCHAR2(100) NOT NULL,
                          hire_date DATE,

                          CONSTRAINT PK_MANAGERS PRIMARY KEY (manager_id)
);

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),
                             manager_id NUMBER,    -- Nullable (Some departments have no manager)

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id),

                             CONSTRAINT FK_DEPARTMENT_MANAGER
                                 FOREIGN KEY (manager_id)
                                     REFERENCES Managers(manager_id)
);

-------------------------------------------------
-- Insert sample managers
-------------------------------------------------

INSERT INTO Managers (manager_name, hire_date)
VALUES ('Ahmed Hassan', DATE '2020-01-15');

INSERT INTO Managers (manager_name, hire_date)
VALUES ('Sara Ali', DATE '2019-06-20');

INSERT INTO Managers (manager_name, hire_date)
VALUES ('Mohamed Salah', DATE '2021-03-10');

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (department_name, location, manager_id)
VALUES ('IT', 'Cairo', 1);

INSERT INTO Departments (department_name, location, manager_id)
VALUES ('HR', 'Alexandria', 2);

INSERT INTO Departments (department_name, location, manager_id)
VALUES ('Finance', 'Giza', 3);

-- Departments without a manager
INSERT INTO Departments (department_name, location, manager_id)
VALUES ('Marketing', 'Assiut', NULL);

INSERT INTO Departments (department_name, location, manager_id)
VALUES ('Sales', 'Luxor', NULL);

-------------------------------------------------
-- View data using LEFT OUTER JOIN
-------------------------------------------------

SELECT d.department_name, d.location,
       m.manager_name
FROM Departments d
         LEFT OUTER JOIN Managers m
                         ON d.manager_id = m.manager_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- List all books and their authors from the books and authors tables.
-- Include books that don’t have an assigned author using a LEFT JOIN.

DROP TABLE Books;
DROP TABLE Authors;

-- Create Authors table
CREATE TABLE Authors (
                         author_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         author_name VARCHAR2(100) NOT NULL,
                         country VARCHAR2(50),

                         CONSTRAINT PK_AUTHORS PRIMARY KEY (author_id)
);

-- Create Books table
CREATE TABLE Books (
                       book_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       book_name VARCHAR2(100) NOT NULL,
                       price NUMBER,
                       author_id NUMBER,    -- Nullable (Some books have no assigned author)

                       CONSTRAINT PK_BOOKS PRIMARY KEY (book_id),

                       CONSTRAINT FK_BOOK_AUTHOR
                           FOREIGN KEY (author_id)
                               REFERENCES Authors(author_id)
);

-------------------------------------------------
-- Insert sample authors
-------------------------------------------------

INSERT INTO Authors (author_name, country)
VALUES ('Robert Martin', 'USA');

INSERT INTO Authors (author_name, country)
VALUES ('Thomas Cormen', 'USA');

INSERT INTO Authors (author_name, country)
VALUES ('Andrew Tanenbaum', 'Netherlands');

INSERT INTO Authors (author_name, country)
VALUES ('Martin Fowler', 'UK');

-------------------------------------------------
-- Insert sample books
-------------------------------------------------

INSERT INTO Books (book_name, price, author_id)
VALUES ('Clean Code', 50, 1);

INSERT INTO Books (book_name, price, author_id)
VALUES ('Introduction to Algorithms', 80, 2);

INSERT INTO Books (book_name, price, author_id)
VALUES ('Modern Operating Systems', 65, 3);

INSERT INTO Books (book_name, price, author_id)
VALUES ('Refactoring', 70, 4);

-- Books without an assigned author
INSERT INTO Books (book_name, price, author_id)
VALUES ('Database Fundamentals', 45, NULL);

INSERT INTO Books (book_name, price, author_id)
VALUES ('Cloud Computing Basics', 55, NULL);

-------------------------------------------------
-- View data using LEFT OUTER JOIN
-------------------------------------------------

SELECT b.book_name, a.author_name
FROM Books b
         LEFT OUTER JOIN Authors a
                         ON b.author_id = a.author_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- Write a query that retrieves all invoices along with their corresponding payment status.
-- Use LEFT JOIN to include invoices with no payment.

DROP TABLE Payments;
DROP TABLE Invoices;

-- Create Invoices table
CREATE TABLE Invoices (
                          invoice_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          invoice_date DATE,
                          total_amount NUMBER,

                          CONSTRAINT PK_INVOICES PRIMARY KEY (invoice_id)
);

-- Create Payments table
CREATE TABLE Payments (
                          payment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          payment_date DATE,
                          amount NUMBER,
                          invoice_id NUMBER,    -- Nullable (Some invoices have no payment)

                          CONSTRAINT PK_PAYMENTS PRIMARY KEY (payment_id),

                          CONSTRAINT FK_PAYMENT_INVOICE
                              FOREIGN KEY (invoice_id)
                                  REFERENCES Invoices(invoice_id)
);

-------------------------------------------------
-- Insert sample invoices
-------------------------------------------------

INSERT INTO Invoices (invoice_date, total_amount)
VALUES (DATE '2026-07-01', 1500);

INSERT INTO Invoices (invoice_date, total_amount)
VALUES (DATE '2026-07-02', 2200);

INSERT INTO Invoices (invoice_date, total_amount)
VALUES (DATE '2026-07-03', 1800);

INSERT INTO Invoices (invoice_date, total_amount)
VALUES (DATE '2026-07-04', 3200);

INSERT INTO Invoices (invoice_date, total_amount)
VALUES (DATE '2026-07-05', 950);

-------------------------------------------------
-- Insert sample payments
-------------------------------------------------

INSERT INTO Payments (payment_date, amount, invoice_id)
VALUES (DATE '2026-07-02', 1500, 1);

INSERT INTO Payments (payment_date, amount, invoice_id)
VALUES (DATE '2026-07-03', 2200, 2);

INSERT INTO Payments (payment_date, c, invoice_id)
VALUES (DATE '2026-07-05', 3200, 4);

-- Invoice 3 and Invoice 5 have no payment

-------------------------------------------------
-- View data using LEFT OUTER JOIN
-------------------------------------------------

SELECT i.invoice_id, i.invoice_date, i.total_amount AS Invoice_total_amount,
       p.payment_id, p.payment_date, p.amount AS Payment_Amoun
FROM Invoices i
         LEFT OUTER JOIN Payments p
                         ON i.invoice_id = p.invoice_id;

-- ---------------------------------------------------------------------------------------------------------------------
-- Get all employees and their projects from employees and projects_assigned tables.
-- Include employees who are not assigned to any project.

DROP TABLE Employees;
DROP TABLE Projects;

-- Create Projects table
CREATE TABLE Projects (
                          project_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          project_name VARCHAR2(100) NOT NULL,
                          start_date DATE,

                          CONSTRAINT PK_PROJECTS PRIMARY KEY (project_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           project_id NUMBER,    -- Nullable (Some employees are not assigned to any project)

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_PROJECT
                               FOREIGN KEY (project_id)
                                   REFERENCES Projects(project_id)
);

-------------------------------------------------
-- Insert sample projects
-------------------------------------------------

INSERT INTO Projects (project_name, start_date)
VALUES ('Inventory System', DATE '2026-07-01');

INSERT INTO Projects (project_name, start_date)
VALUES ('E-Commerce Website', DATE '2026-07-05');

INSERT INTO Projects (project_name, start_date)
VALUES ('Hospital Management', DATE '2026-07-10');

INSERT INTO Projects (project_name, start_date)
VALUES ('HR System', DATE '2026-07-15');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Mostafa', 18000, 1);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Ahmed', 15000, 2);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Sara', 12000, 3);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Mona', 22000, 4);

-- Employees without a project
INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Ali', 14000, NULL);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Omar', 16000, NULL);

-------------------------------------------------
-- View data using LEFT OUTER JOIN
-------------------------------------------------

SELECT e.employee_name, e.salary AS Employee_Salary,
       p.project_name, p.start_date
FROM Employees e
         LEFT OUTER JOIN Projects p
                         ON e.project_id = p.project_id;

