-- Find all employees who earn more than at least one employee in department 10.
-- Use a subquery with ANY or SOME.

DROP TABLE Employees;
DROP TABLE Departments;

-------------------------------------------------
-- Create Departments table
-------------------------------------------------

CREATE TABLE Departments (
                             department_id NUMBER PRIMARY KEY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100)
);

-------------------------------------------------
-- Create Employees table
-------------------------------------------------

CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments VALUES (1, 'Human Resources', 'Cairo');
INSERT INTO Departments VALUES (2, 'Finance', 'Alexandria');
INSERT INTO Departments VALUES (3, 'Sales', 'Giza');
INSERT INTO Departments VALUES (4, 'Marketing', 'Assiut');
INSERT INTO Departments VALUES (5, 'IT', 'Luxor');

-- Department with ID = 10
INSERT INTO Departments VALUES (10, 'Research', 'New Cairo');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('John Smith', 12000, DATE '2022-01-15', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ahmed Mohamed', 15000, DATE '2021-03-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara Ali', 10000, DATE '2020-07-18', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali Mahmoud', 11000, DATE '2022-09-30', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20', 10);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Hana Samir', 15500, DATE '2023-08-14', 10);

SELECT *
FROM Employees e
WHERE e.salary < ALL(
    SELECT min(e1.salary)
    FROM Employees e1
    WHERE e1.department_id = 10
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Display products that have a price equal to any product in the 'Electronics' category.
-- Use a subquery inside an IN clause.

DROP TABLE Employees;
DROP TABLE Departments;

-------------------------------------------------
-- Create Departments table
-------------------------------------------------

CREATE TABLE Departments (
                             department_id NUMBER PRIMARY KEY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100)
);

-------------------------------------------------
-- Create Employees table
-------------------------------------------------

CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments VALUES (1, 'Human Resources', 'Cairo');
INSERT INTO Departments VALUES (2, 'Finance', 'Alexandria');
INSERT INTO Departments VALUES (3, 'Sales', 'Giza');
INSERT INTO Departments VALUES (4, 'Marketing', 'Assiut');
INSERT INTO Departments VALUES (5, 'IT', 'Luxor');

-- Department with ID = 20
INSERT INTO Departments VALUES (20, 'Research', 'New Cairo');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('John Smith', 18000, DATE '2022-01-15', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ahmed Mohamed', 15000, DATE '2021-03-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara Ali', 17000, DATE '2020-07-18', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali Mahmoud', 16000, DATE '2022-09-30', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20', 20);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Hana Samir', 15500, DATE '2023-08-14', 20);

SELECT *
FROM Employees e
WHERE e.salary < ALL(
    SELECT min(e1.salary)
    FROM Employees e1
    WHERE e1.department_id = 20
);



-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Display products that have a price equal to any product in the 'Electronics' category.
-- Use a subquery inside an IN clause.


DROP TABLE Products;

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          category VARCHAR2(100) NOT NULL,
                          price NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-------------------------------------------------
-- Insert sample data
-------------------------------------------------

INSERT INTO Products (product_name, category, price)
VALUES ('Laptop', 'Electronics', 25000);

INSERT INTO Products (product_name, category, price)
VALUES ('Monitor', 'Electronics', 7000);

INSERT INTO Products (product_name, category, price)
VALUES ('Mouse', 'Accessories', 350);

INSERT INTO Products (product_name, category, price)
VALUES ('Keyboard', 'Accessories', 350);

INSERT INTO Products (product_name, category, price)
VALUES ('Headphones', 'Accessories', 7000);

INSERT INTO Products (product_name, category, price)
VALUES ('USB Flash Drive', 'Accessories', 350);

INSERT INTO Products (product_name, category, price)
VALUES ('Office Chair', 'Furniture', 4500);

INSERT INTO Products (product_name, category, price)
VALUES ('Desk', 'Furniture', 7000);

INSERT INTO Products (product_name, category, price)
VALUES ('Printer', 'Office', 3800);

INSERT INTO Products (product_name, category, price)
VALUES ('Scanner', 'Office', 25000);


SELECT *
FROM Products p
WHERE p.price IN (
    SELECT p1.price
    FROM Products p1
    WHERE p1.category = 'Electronics'
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Retrieve names of customers who have placed an order for a product with price greater than $1000.
-- Use a subquery with IN or EXISTS.

DROP TABLE Orders;
DROP TABLE Products;
DROP TABLE Customers;

-------------------------------------------------
-- Create Customers table
-------------------------------------------------

CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           city VARCHAR2(100),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-------------------------------------------------
-- Create Products table
-------------------------------------------------

CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          category CHAR(1) NOT NULL,
                          price NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-------------------------------------------------
-- Create Orders table
-------------------------------------------------

CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE NOT NULL,
                        quantity NUMBER NOT NULL,
                        customer_id NUMBER NOT NULL,
                        product_id NUMBER NOT NULL,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),

                        CONSTRAINT FK_ORDER_CUSTOMER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id),

                        CONSTRAINT FK_ORDER_PRODUCT
                            FOREIGN KEY (product_id)
                                REFERENCES Products(product_id)
);

-------------------------------------------------
-- Insert sample customers
-------------------------------------------------

INSERT INTO Customers (customer_name, city)
VALUES ('John Smith', 'New York');

INSERT INTO Customers (customer_name, city)
VALUES ('Mostafa Talat', 'Cairo');

INSERT INTO Customers (customer_name, city)
VALUES ('Ahmed Mohamed', 'Alexandria');

INSERT INTO Customers (customer_name, city)
VALUES ('Sara Ali', 'Giza');

INSERT INTO Customers (customer_name, city)
VALUES ('Mona Hassan', 'Luxor');

INSERT INTO Customers (customer_name, city)
VALUES ('Ali Mahmoud', 'Assiut');

INSERT INTO Customers (customer_name, city)
VALUES ('Omar Khaled', 'Aswan');

INSERT INTO Customers (customer_name, city)
VALUES ('Hana Samir', 'Tanta');

-------------------------------------------------
-- Insert sample products
-------------------------------------------------

INSERT INTO Products (product_name, category, price)
VALUES ('Laptop', 'A', 25000);

INSERT INTO Products (product_name, category, price)
VALUES ('Mouse', 'A', 500);

INSERT INTO Products (product_name, category, price)
VALUES ('Keyboard', 'A', 1500);

INSERT INTO Products (product_name, category, price)
VALUES ('Monitor', 'B', 6500);

INSERT INTO Products (product_name, category, price)
VALUES ('Printer', 'B', 4200);

INSERT INTO Products (product_name, category, price)
VALUES ('Desk', 'C', 2000);

INSERT INTO Products (product_name, category, price)
VALUES ('Office Chair', 'C', 3200);

INSERT INTO Products (product_name, category, price)
VALUES ('Scanner', 'B', 2800);

-------------------------------------------------
-- Insert sample orders
-------------------------------------------------

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-01', 1, 2, 1);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-02', 2, 3, 2);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-03', 1, 4, 3);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-04', 3, 4, 4);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-05', 2, 5, 5);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-06', 1, 6, 6);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-07', 4, 7, 1);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-08', 2, 8, 7);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-09', 1, 5, 8);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-10', 5, 2, 3);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-11', 2, 3, 2);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-12', 1, 4, 5);

SELECT *
FROM Customers c
WHERE EXISTS (
    SELECT *
    FROM Orders o
    WHERE o.customer_id = c.customer_id
      AND o.product_id IN (
        SELECT product_id
        FROM Products
        WHERE price > 1000
    )
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- List the employees who work in the same job titles as at least one other employee.
-- Use a subquery with IN on job titles.
DROP TABLE Employees;

-------------------------------------------------
-- Create Employees table
-------------------------------------------------

CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           job_title VARCHAR2(100),

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id)
);

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('John Smith', 25000, DATE '2020-01-15', 'Software Engineer');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Ahmed Mohamed', 22000, DATE '2021-03-10', 'Software Engineer');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Sara Ali', 30000, DATE '2019-07-18', 'Project Manager');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Mona Hassan', 28000, DATE '2023-05-12', 'Project Manager');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Ali Mahmoud', 18000, DATE '2021-09-30', 'Database Administrator');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Hana Samir', 16000, DATE '2023-08-14', 'QA Engineer');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Youssef Adel', 16500, DATE '2020-12-01', 'QA Engineer');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Nada Ibrahim', 15000, DATE '2018-06-25', 'Technical Support');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Khaled Samy', 15500, DATE '2022-02-17', 'Technical Support');

INSERT INTO Employees (employee_name, salary, hire_date, job_title)
VALUES ('Nour Ahmed', 24000, DATE '2021-08-05', 'DevOps Engineer');

SELECT *
FROM Employees e
WHERE e.job_title IN (
    SELECT e1.job_title
    FROM Employees e1
    WHERE e.job_title = e1.job_title
      AND e.employee_id != e1.employee_id
    );


-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Find the departments that have more than one employee.
-- Use a subquery with GROUP BY and HAVING, or join with a subquery returning multiple department IDs.

DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (department_name, location)
VALUES ('Human Resources', 'Cairo');

INSERT INTO Departments (department_name, location)
VALUES ('IT', 'Alexandria');

INSERT INTO Departments (department_name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (department_name, location)
VALUES ('Sales', 'Assiut');

INSERT INTO Departments (department_name, location)
VALUES ('Marketing', 'Luxor');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('John Smith', 18000, DATE '2022-01-15', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Alice', 15000, DATE '2021-03-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara Ali', 17000, DATE '2020-07-18', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa Talat', 22000, DATE '2019-11-25', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali Mahmoud', 16000, DATE '2022-09-30', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Hana Samir', 15500, DATE '2023-08-14', 3);

SELECT d.department_name AS department_name,
       count(e.department_id)
FROM departments d
         JOIN Employees e
              ON d.department_id = e.department_id
GROUP BY d.department_id, d.department_name
HAVING count(e.department_id) > 1;


-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Show all orders placed by customers who are from cities where other customers have placed orders too.
-- Use a correlated subquery or a multiple-row subquery with IN.

DROP TABLE Orders;
DROP TABLE Products;
DROP TABLE Customers;

-------------------------------------------------
-- Create Customers table
-------------------------------------------------

CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           city VARCHAR2(100),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-------------------------------------------------
-- Create Products table
-------------------------------------------------

CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          category CHAR(1) NOT NULL,
                          price NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-------------------------------------------------
-- Create Orders table
-------------------------------------------------

CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE NOT NULL,
                        quantity NUMBER NOT NULL,
                        customer_id NUMBER NOT NULL,
                        product_id NUMBER NOT NULL,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),

                        CONSTRAINT FK_ORDER_CUSTOMER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id),

                        CONSTRAINT FK_ORDER_PRODUCT
                            FOREIGN KEY (product_id)
                                REFERENCES Products(product_id)
);
-------------------------------------------------
-- Insert sample customers
-------------------------------------------------

INSERT INTO Customers (customer_name, city)
VALUES ('John Smith', 'New York');

INSERT INTO Customers (customer_name, city)
VALUES ('Ahmed Mohamed', 'New York');

INSERT INTO Customers (customer_name, city)
VALUES ('Mostafa Talat', 'Cairo');

INSERT INTO Customers (customer_name, city)
VALUES ('Sara Ali', 'Cairo');

INSERT INTO Customers (customer_name, city)
VALUES ('Mona Hassan', 'Luxor');

INSERT INTO Customers (customer_name, city)
VALUES ('Ali Mahmoud', 'Alexandria');

INSERT INTO Customers (customer_name, city)
VALUES ('Omar Khaled', 'Alexandria');

INSERT INTO Customers (customer_name, city)
VALUES ('Hana Samir', 'Aswan');

-------------------------------------------------
-- Insert sample products
-------------------------------------------------

INSERT INTO Products (product_name, category, price)
VALUES ('Laptop', 'A', 25000);

INSERT INTO Products (product_name, category, price)
VALUES ('Mouse', 'A', 500);

INSERT INTO Products (product_name, category, price)
VALUES ('Keyboard', 'A', 1500);

INSERT INTO Products (product_name, category, price)
VALUES ('Monitor', 'B', 6500);

INSERT INTO Products (product_name, category, price)
VALUES ('Printer', 'B', 4200);

INSERT INTO Products (product_name, category, price)
VALUES ('Desk', 'C', 2000);

-------------------------------------------------
-- Insert sample orders
-------------------------------------------------

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-01', 1, 1, 1);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-02', 2, 2, 2);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-03', 1, 3, 3);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-04', 3, 4, 4);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-05', 2, 5, 5);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-06', 1, 6, 6);

INSERT INTO Orders (order_date, quantity, customer_id, product_id)
VALUES (DATE '2026-07-07', 4, 7, 1);

SELECT *
FROM Orders o
WHERE o.customer_id IN (
    SELECT c.customer_id
    FROM Customers c
    WHERE c.city IN (
        SELECT c1.city
        FROM Customers c1
                 JOIN Orders o1
                      ON c1.customer_id = o1.customer_id
        GROUP BY c1.city
        HAVING count(DISTINCT c1.customer_id) > 1
    )
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- List all books that were written by authors who have published more than one book.
-- Use a subquery with GROUP BY and HAVING.


DROP TABLE Books;
DROP TABLE Authors;

-- Create Authors table
CREATE TABLE Authors (
                         author_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         author_name VARCHAR2(100) NOT NULL,
                         country VARCHAR2(50),

                         CONSTRAINT PK_AUTHORS PRIMARY KEY (author_id)
);

-- Create Books table
CREATE TABLE Books (
                       book_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       book_name VARCHAR2(100) NOT NULL,
                       price NUMBER,
                       author_id NUMBER,    -- Nullable (Some books have no assigned author)

                       CONSTRAINT PK_BOOKS PRIMARY KEY (book_id),

                       CONSTRAINT FK_BOOK_AUTHOR
                           FOREIGN KEY (author_id)
                               REFERENCES Authors(author_id)
);

-------------------------------------------------
-- Insert sample authors
-------------------------------------------------

INSERT INTO Authors (author_name, country)
VALUES ('Robert Martin', 'USA');

INSERT INTO Authors (author_name, country)
VALUES ('Thomas Cormen', 'USA');

INSERT INTO Authors (author_name, country)
VALUES ('Andrew Tanenbaum', 'Netherlands');

INSERT INTO Authors (author_name, country)
VALUES ('Martin Fowler', 'UK');

-------------------------------------------------
-- Insert sample books
-------------------------------------------------

INSERT INTO Books (book_name, price, author_id)
VALUES ('Clean Code', 50, 1);

INSERT INTO Books (book_name, price, author_id)
VALUES ('Refactoring', 70, 4);

-- Books without an assigned author
INSERT INTO Books (book_name, price, author_id)
VALUES ('Database Fundamentals', 45, 1);

INSERT INTO Books (book_name, price, author_id)
VALUES ('Cloud Computing Basics', 55, 4);


SELECT *
FROM Books
WHERE author_id IN (
    SELECT b.author_id
    FROM books b
    GROUP BY b.author_id
    HAVING count(author_id) > 1
);

-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Display the names of students who are enrolled in any of the courses taught by professor 'Dr. Smith'.
-- Use a subquery to get course IDs.


DROP TABLE Students;
DROP TABLE Courses;

-- Create Courses table
CREATE TABLE Courses (
                         course_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         course_name VARCHAR2(100) NOT NULL,
                         professor_name VARCHAR2(100) NOT NULL,
                         CONSTRAINT PK_COURSES PRIMARY KEY (course_id)
);

-- Create Students table
CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          student_name VARCHAR2(100) NOT NULL,
                          age NUMBER,
                          course_id NUMBER,    -- Nullable (Some students are not enrolled in any course)

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id),

                          CONSTRAINT FK_STUDENT_COURSE
                              FOREIGN KEY (course_id)
                                  REFERENCES Courses(course_id)
);

-------------------------------------------------
-- Insert sample courses
-------------------------------------------------

INSERT INTO Courses (course_name, professor_name)
VALUES ('Database Systems', 'Dr. Smith');

INSERT INTO Courses (course_name, professor_name)
VALUES ('Data Structures', 'Dr. Johnson');

INSERT INTO Courses (course_name, professor_name)
VALUES ('Operating Systems', 'Dr. Smith');

INSERT INTO Courses (course_name, professor_name)
VALUES ('Software Engineering', 'Dr. Brown');

INSERT INTO Courses (course_name, professor_name)
VALUES ('Computer Networks', 'Dr. Smith');

-------------------------------------------------
-- Insert sample students
-------------------------------------------------

INSERT INTO Students (student_name, age, course_id)
VALUES ('John Smith', 20, 1);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Ahmed Mohamed', 21, 1);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Mostafa Talat', 22, 2);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Sara Ali', 20, 3);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Mona Hassan', 21, 3);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Ali Mahmoud', 23, 4);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Omar Khaled', 19, 5);

-- Students not enrolled in any course
INSERT INTO Students (student_name, age, course_id)
VALUES ('Hana Samir', 20, 2);

INSERT INTO Students (student_name, age, course_id)
VALUES ('Youssef Adel', 22, 2);

SELECT student_name
FROM Students
WHERE course_id = ANY (
    SELECT course_id
    FROM Courses
    WHERE professor_name = 'Dr. Smith'
);


-- --------------------------------------------------------------------------------------------------------------------------------------------
-- Retrieve all employees whose salary matches any of the salaries in department 30.
-- Use a subquery with IN.

DROP TABLE Employees;
DROP TABLE Departments;

-------------------------------------------------
-- Create Departments table
-------------------------------------------------

CREATE TABLE Departments (
                             department_id NUMBER PRIMARY KEY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100)
);

-------------------------------------------------
-- Create Employees table
-------------------------------------------------

CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           hire_date DATE,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments VALUES (1, 'Human Resources', 'Cairo');
INSERT INTO Departments VALUES (2, 'Finance', 'Alexandria');
INSERT INTO Departments VALUES (3, 'Sales', 'Giza');
INSERT INTO Departments VALUES (4, 'Marketing', 'Assiut');
INSERT INTO Departments VALUES (5, 'IT', 'Luxor');

-- Department with ID = 30
INSERT INTO Departments VALUES (30, 'Research', 'New Cairo');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('John Smith', 12000, DATE '2022-01-15', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ahmed Mohamed', 15500, DATE '2021-03-10', 1);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Sara Ali', 15500, DATE '2020-07-18', 2);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mostafa Talat', 13500, DATE '2019-11-25', 5);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Mona Hassan', 14000, DATE '2023-05-12', 3);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Ali Mahmoud', 13500, DATE '2022-09-30', 4);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Omar Khaled', 13500, DATE '2024-02-20', 30);

INSERT INTO Employees (employee_name, salary, hire_date, department_id)
VALUES ('Hana Samir', 15500, DATE '2023-08-14', 30);


SELECT *
FROM Employees
WHERE salary IN (
    SELECT e.salary
    FROM Employees e
    WHERE e.department_id = 30

);