-- Write a query to display the names of employees and their department names using a natural join.


-- Create Departments table
CREATE TABLE Departments (
                             dept_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             dept_name VARCHAR2(100) NOT NULL,

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (dept_id),
                             CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (dept_name)
);

-- Create Employees table
CREATE TABLE Employees (
                           emp_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           emp_name VARCHAR2(100) NOT NULL,
                           salary NUMBER CHECK (salary > 0),
                           dept_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (emp_id),
                           CONSTRAINT FK_EMP_DEPT
                               FOREIGN KEY (dept_id)
                                   REFERENCES Departments(dept_id)
);


-- Departments
INSERT INTO Departments (dept_name) VALUES ('IT');
INSERT INTO Departments (dept_name) VALUES ('HR');
INSERT INTO Departments (dept_name) VALUES ('Finance');
INSERT INTO Departments (dept_name) VALUES ('Sales');
INSERT INTO Departments (dept_name) VALUES ('Marketing');
INSERT INTO Departments (dept_name) VALUES ('Operations');
INSERT INTO Departments (dept_name) VALUES ('Customer Support');
INSERT INTO Departments (dept_name) VALUES ('Research');
INSERT INTO Departments (dept_name) VALUES ('Legal');
INSERT INTO Departments (dept_name) VALUES ('Administration');


-- Employees
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Mostafa', 8000, 1);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Ahmed', 6500, 1);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Mohamed', 7200, 2);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Omar', 5000, 2);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Ali', 9000, 3);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Sara', 7500, 3);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Mona', 6200, 4);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Youssef', 6800, 4);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Hassan', 8100, 5);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Nour', 5900, 5);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Karim', 9300, 6);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Aya', 7100, 6);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Salma', 5400, 7);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Ibrahim', 6700, 7);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Hoda', 8800, 8);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Mahmoud', 7900, 8);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Rania', 6100, 9);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Amr', 9500, 9);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Fatma', 7000, 10);
INSERT INTO Employees (emp_name, salary, dept_id) VALUES ('Khaled', 8400, 10);

SELECT emp_name, dept_name FROM Employees NATURAL JOIN Departments; -- by dept_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to list all orders with their corresponding customer names using a natural join.

-- Create Customers table
CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           email VARCHAR2(150) UNIQUE,
                           phone VARCHAR2(20),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-- Create Orders table
CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE DEFAULT SYSDATE,
                        total_amount NUMBER,
                        customer_id NUMBER NOT NULL,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),
                        CONSTRAINT CH_TOTAL_AMOUNT CHECK (total_amount >= 0),
                        CONSTRAINT FK_CUSTOMER_ORDER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id)
);

-- Customers
INSERT INTO Customers (customer_name, email, phone)
VALUES ('Mostafa', 'mostafa@gmail.com', '01000000001');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Ahmed', 'ahmed@gmail.com', '01000000002');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Mohamed', 'mohamed@gmail.com', '01000000003');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Sara', 'sara@gmail.com', '01000000004');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Mona', 'mona@gmail.com', '01000000005');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Omar', 'omar@gmail.com', '01000000006');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Aya', 'aya@gmail.com', '01000000007');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Youssef', 'youssef@gmail.com', '01000000008');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Fatma', 'fatma@gmail.com', '01000000009');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Ali', 'ali@gmail.com', '01000000010');


-- Orders
INSERT INTO Orders (total_amount, customer_id) VALUES (250, 1);
INSERT INTO Orders (total_amount, customer_id) VALUES (500, 1);
INSERT INTO Orders (total_amount, customer_id) VALUES (1200, 2);
INSERT INTO Orders (total_amount, customer_id) VALUES (350, 3);
INSERT INTO Orders (total_amount, customer_id) VALUES (700, 4);
INSERT INTO Orders (total_amount, customer_id) VALUES (150, 5);
INSERT INTO Orders (total_amount, customer_id) VALUES (450, 6);
INSERT INTO Orders (total_amount, customer_id) VALUES (980, 7);
INSERT INTO Orders (total_amount, customer_id) VALUES (320, 8);
INSERT INTO Orders (total_amount, customer_id) VALUES (890, 9);
INSERT INTO Orders (total_amount, customer_id) VALUES (650, 10);
INSERT INTO Orders (total_amount, customer_id) VALUES (200, 2);
INSERT INTO Orders (total_amount, customer_id) VALUES (1750, 3);
INSERT INTO Orders (total_amount, customer_id) VALUES (430, 4);
INSERT INTO Orders (total_amount, customer_id) VALUES (990, 5);


SELECT order_id,total_amount,order_date, customer_name FROM Orders NATURAL JOIN Customers; -- by customer_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to show student names and the courses they are enrolled in using a natural join.

CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          student_name VARCHAR2(100) NOT NULL,
                          age NUMBER CHECK (age >= 18),
                          city VARCHAR2(50),

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id)
);

CREATE TABLE Courses (
                         course_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         course_name VARCHAR2(100) NOT NULL,
                         credit_hours NUMBER CHECK (credit_hours > 0),
                         student_id NUMBER NOT NULL,

                         CONSTRAINT PK_COURSES PRIMARY KEY (course_id),
                         CONSTRAINT FK_STUDENT_COURSE
                             FOREIGN KEY (student_id)
                                 REFERENCES Students(student_id)
);

-- Students
INSERT INTO Students (student_name, age, city)
VALUES ('Mostafa', 23, 'Cairo');

INSERT INTO Students (student_name, age, city)
VALUES ('Ahmed', 21, 'Alexandria');

INSERT INTO Students (student_name, age, city)
VALUES ('Sara', 20, 'Giza');

INSERT INTO Students (student_name, age, city)
VALUES ('Mona', 22, 'Assiut');

INSERT INTO Students (student_name, age, city)
VALUES ('Omar', 24, 'Luxor');

-- Courses
INSERT INTO Courses (course_name, credit_hours, student_id)
VALUES ('Database Systems', 3, 1);

INSERT INTO Courses (course_name, credit_hours, student_id)
VALUES ('Java Programming', 4, 1);

INSERT INTO Courses (course_name, credit_hours, student_id)
VALUES ('Operating Systems', 3, 2);

INSERT INTO Courses (course_name, credit_hours, student_id)
VALUES ('Computer Networks', 3, 3);

INSERT INTO Courses (course_name, credit_hours, student_id)
VALUES ('Software Engineering', 4, 4);

INSERT INTO Courses (course_name, credit_hours, student_id)
VALUES ('Data Structures', 3, 5);

INSERT INTO Courses (course_name, credit_hours, student_id)
VALUES ('Web Development', 3, 2);

INSERT INTO Courses (course_name, credit_hours, student_id)
VALUES ('Machine Learning', 4, 3);


SELECT student_name, course_name FROM Students NATURAL JOIN  Courses; -- by student_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to display project names and the employees working on them using a natural join.

CREATE TABLE Projects (
                          project_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          project_name VARCHAR2(100) NOT NULL,
                          budget NUMBER,

                          CONSTRAINT PK_PROJECTS PRIMARY KEY (project_id)
);

CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           project_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),
                           CONSTRAINT FK_EMPLOYEE_PROJECT
                               FOREIGN KEY (project_id)
                                   REFERENCES Projects(project_id)
);


-- Insert Projects
INSERT INTO Projects (project_name, budget)
VALUES ('E-Commerce System', 500000);

INSERT INTO Projects (project_name, budget)
VALUES ('Hospital Management', 750000);

INSERT INTO Projects (project_name, budget)
VALUES ('Banking System', 1200000);

INSERT INTO Projects (project_name, budget)
VALUES ('School Management', 300000);

-- Insert Employees
INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Mostafa', 12000, 1);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Ahmed', 10000, 1);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Sara', 11000, 2);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Mona', 9500, 2);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Omar', 15000, 3);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Ali', 13000, 3);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Nour', 9000, 4);

SELECT project_name, employee_name FROM Projects NATURAL JOIN Employees; -- BY project_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to retrieve invoice details along with product names using a natural join.

DROP TABLE Invoices;
DROP TABLE Products;

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          price NUMBER,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-- Create Invoices table
CREATE TABLE Invoices (
                          invoice_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          invoice_date DATE DEFAULT SYSDATE,
                          quantity NUMBER,
                          product_id NUMBER NOT NULL,

                          CONSTRAINT PK_INVOICES PRIMARY KEY (invoice_id),
                          CONSTRAINT FK_INVOICE_PRODUCT
                              FOREIGN KEY (product_id)
                                  REFERENCES Products(product_id)
);

-- Products
INSERT INTO Products (product_name, price) VALUES ('Laptop', 25000);
INSERT INTO Products (product_name, price) VALUES ('Mouse', 500);
INSERT INTO Products (product_name, price) VALUES ('Keyboard', 900);
INSERT INTO Products (product_name, price) VALUES ('Monitor', 4500);
INSERT INTO Products (product_name, price) VALUES ('Printer', 3200);

-- Invoices
INSERT INTO Invoices (quantity, product_id) VALUES (2,1);
INSERT INTO Invoices (quantity, product_id) VALUES (5,2);
INSERT INTO Invoices (quantity, product_id) VALUES (3,3);
INSERT INTO Invoices (quantity, product_id) VALUES (1,4);
INSERT INTO Invoices (quantity, product_id) VALUES (2,5);

SELECT invoice_id, invoice_date, quantity, product_name FROM Invoices NATURAL JOIN Products; -- by product_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to find all books with their respective author names using a natural join.

DROP TABLE Books;
DROP TABLE Authors;

-- Create Authors table
CREATE TABLE Authors (
                         author_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         author_name VARCHAR2(100) NOT NULL,

                         CONSTRAINT PK_AUTHORS PRIMARY KEY (author_id)
);

-- Create Books table
CREATE TABLE Books (
                       book_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       book_name VARCHAR2(100),
                       author_id NUMBER NOT NULL,

                       CONSTRAINT PK_BOOKS PRIMARY KEY (book_id),
                       CONSTRAINT FK_BOOK_AUTHOR
                           FOREIGN KEY (author_id)
                               REFERENCES Authors(author_id)
);

-- Authors
INSERT INTO Authors (author_name) VALUES ('Ahmed Khaled');
INSERT INTO Authors (author_name) VALUES ('Naguib Mahfouz');
INSERT INTO Authors (author_name) VALUES ('Taha Hussein');
INSERT INTO Authors (author_name) VALUES ('Mostafa Mahmoud');
INSERT INTO Authors (author_name) VALUES ('Paulo Coelho');

-- Books
INSERT INTO Books (book_name, author_id) VALUES ('Book A',1);
INSERT INTO Books (book_name, author_id) VALUES ('Book B',2);
INSERT INTO Books (book_name, author_id) VALUES ('Book C',3);
INSERT INTO Books (book_name, author_id) VALUES ('Book D',4);
INSERT INTO Books (book_name, author_id) VALUES ('Book E',5);

SELECT book_name, author_name FROM Books NATURAL JOIN Authors; -- by author_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to list all class schedules along with their instructors' names using a natural join.

DROP TABLE Class_Schedules;
DROP TABLE Instructors;

-- Create Instructors table
CREATE TABLE Instructors (
                             instructor_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             instructor_name VARCHAR2(100),

                             CONSTRAINT PK_INSTRUCTORS PRIMARY KEY (instructor_id)
);

-- Create Class Schedules table
CREATE TABLE Class_Schedules (
                                 schedule_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                                 class_name VARCHAR2(100),
                                 class_time VARCHAR2(30),
                                 instructor_id NUMBER NOT NULL,

                                 CONSTRAINT PK_CLASS_SCHEDULE PRIMARY KEY (schedule_id),
                                 CONSTRAINT FK_CLASS_INSTRUCTOR
                                     FOREIGN KEY (instructor_id)
                                         REFERENCES Instructors(instructor_id)
);

-- Instructors
INSERT INTO Instructors (instructor_name) VALUES ('Mostafa');
INSERT INTO Instructors (instructor_name) VALUES ('Ahmed');
INSERT INTO Instructors (instructor_name) VALUES ('Sara');

-- Class Schedules
INSERT INTO Class_Schedules (class_name,class_time,instructor_id)
VALUES ('Database','09:00 AM',1);

INSERT INTO Class_Schedules (class_name,class_time,instructor_id)
VALUES ('Java','11:00 AM',2);

INSERT INTO Class_Schedules (class_name,class_time,instructor_id)
VALUES ('Networking','02:00 PM',3);

SELECT class_name, class_time, instructor_name FROM Class_Schedules NATURAL JOIN Instructors;-- by instructor_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to show supplier names and the products they supply using a natural join.

DROP TABLE Products;
DROP TABLE Suppliers;

-- Create Suppliers table
CREATE TABLE Suppliers (
                           supplier_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           supplier_name VARCHAR2(100),

                           CONSTRAINT PK_SUPPLIERS PRIMARY KEY (supplier_id)
);

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100),
                          supplier_id NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id),
                          CONSTRAINT FK_PRODUCT_SUPPLIER
                              FOREIGN KEY (supplier_id)
                                  REFERENCES Suppliers(supplier_id)
);

-- Suppliers
INSERT INTO Suppliers (supplier_name) VALUES ('Dell');
INSERT INTO Suppliers (supplier_name) VALUES ('HP');
INSERT INTO Suppliers (supplier_name) VALUES ('Lenovo');

-- Products
INSERT INTO Products (product_name,supplier_id)
VALUES ('Laptop',1);

INSERT INTO Products (product_name,supplier_id)
VALUES ('Printer',2);

INSERT INTO Products (product_name,supplier_id)
VALUES ('Desktop',3);

SELECT supplier_name, product_name FROM Suppliers NATURAL JOIN Products;-- by supplier_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to display customer orders along with shipping details using a natural join.
DROP TABLE Shipping;
DROP TABLE Orders;

-- Create Orders table
CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE DEFAULT SYSDATE,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id)
);

-- Create Shipping table
CREATE TABLE Shipping (
                          shipping_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          shipping_company VARCHAR2(100),
                          shipping_date DATE,
                          order_id NUMBER NOT NULL,

                          CONSTRAINT PK_SHIPPING PRIMARY KEY (shipping_id),
                          CONSTRAINT FK_SHIPPING_ORDER
                              FOREIGN KEY (order_id)
                                  REFERENCES Orders(order_id)
);

-- Orders
INSERT INTO Orders DEFAULT VALUES;
INSERT INTO Orders DEFAULT VALUES;
INSERT INTO Orders DEFAULT VALUES;

-- Shipping
INSERT INTO Shipping (shipping_company,shipping_date,order_id)
VALUES ('DHL',SYSDATE+1,1);

INSERT INTO Shipping (shipping_company,shipping_date,order_id)
VALUES ('FedEx',SYSDATE+2,2);

INSERT INTO Shipping (shipping_company,shipping_date,order_id)
VALUES ('Aramex',SYSDATE+3,3);

SELECT order_id, order_date, shipping_company, shipping_date FROM Orders NATURAL JOIN Shipping;-- by order_id

-- ------------------------------------------------------------------------------------------------------------------------
-- Write a query to list employees along with their job titles using a natural join.

DROP TABLE Employees;
DROP TABLE Job_Titles;

-- Create Job Titles table
CREATE TABLE Job_Titles (
                            job_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            job_title VARCHAR2(100),

                            CONSTRAINT PK_JOB_TITLES PRIMARY KEY (job_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100),
                           salary NUMBER,
                           job_id NUMBER NOT NULL,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),
                           CONSTRAINT FK_EMPLOYEE_JOB
                               FOREIGN KEY (job_id)
                                   REFERENCES Job_Titles(job_id)
);

-- Job Titles
INSERT INTO Job_Titles (job_title) VALUES ('Software Engineer');
INSERT INTO Job_Titles (job_title) VALUES ('Database Administrator');
INSERT INTO Job_Titles (job_title) VALUES ('Network Engineer');

-- Employees
INSERT INTO Employees (employee_name,salary,job_id)
VALUES ('Mostafa',12000,1);

INSERT INTO Employees (employee_name,salary,job_id)
VALUES ('Ahmed',10000,2);

INSERT INTO Employees (employee_name,salary,job_id)
VALUES ('Sara',11000,3);

SELECT employee_name, job_title FROM Employees NATURAL JOIN Job_Titles;-- by job_id

-- ------------------------------------------------------------------------------------------------------------------------