-- Write a query to display employee names and department names by joining the employees and departments tables using the USING clause on department_id.
DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             department_name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100),

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           department_id NUMBER NOT NULL,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),
                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-- Insert sample departments
INSERT INTO Departments (department_name, location)
VALUES ('IT', 'Cairo');

INSERT INTO Departments (department_name, location)
VALUES ('HR', 'Alexandria');

INSERT INTO Departments (department_name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (department_name, location)
VALUES ('Marketing', 'Assiut');

INSERT INTO Departments (department_name, location)
VALUES ('Sales', 'Mansoura');

-- Insert sample employees
INSERT INTO Employees (employee_name, salary, department_id)
VALUES ('Mostafa', 12000, 1);

INSERT INTO Employees (employee_name, salary, department_id)
VALUES ('Ahmed', 10000, 1);

INSERT INTO Employees (employee_name, salary, department_id)
VALUES ('Sara', 9000, 2);

INSERT INTO Employees (employee_name, salary, department_id)
VALUES ('Mona', 11000, 3);

INSERT INTO Employees (employee_name, salary, department_id)
VALUES ('Ali', 8000, 4);

INSERT INTO Employees (employee_name, salary, department_id)
VALUES ('Omar', 9500, 5);

INSERT INTO Employees (employee_name, salary, department_id)
VALUES ('Nada', 13000, 3);

-- View data using the USING
SELECT * FROM EMPLOYEES JOIN DEPARTMENTS USING (department_id);

-- ----------------------------------------------------------------------------------------
-- Write a query to list all orders and their corresponding customer names using the USING clause on customer_id.

DROP TABLE Orders;
DROP TABLE Customers;

-- Create Customers table
CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           customer_name VARCHAR2(100) NOT NULL,
                           email VARCHAR2(100),
                           phone VARCHAR2(20),

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id)
);

-- Create Orders table
CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        order_date DATE DEFAULT SYSDATE,
                        total_amount NUMBER,
                        customer_id NUMBER NOT NULL,

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id),
                        CONSTRAINT FK_ORDER_CUSTOMER
                            FOREIGN KEY (customer_id)
                                REFERENCES Customers(customer_id)
);

-- Insert sample customers
INSERT INTO Customers (customer_name, email, phone)
VALUES ('Mostafa', 'mostafa@gmail.com', '01011111111');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Ahmed', 'ahmed@gmail.com', '01022222222');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Sara', 'sara@gmail.com', '01033333333');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Mona', 'mona@gmail.com', '01044444444');

INSERT INTO Customers (customer_name, email, phone)
VALUES ('Ali', 'ali@gmail.com', '01055555555');

-- Insert sample orders
INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-01', 2500, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-03', 1200, 2);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-05', 4500, 3);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-08', 800, 1);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-10', 6000, 4);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-12', 1500, 5);

INSERT INTO Orders (order_date, total_amount, customer_id)
VALUES (DATE '2026-07-15', 3200, 2);

-- View data using the USING
order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_date DATE DEFAULT SYSDATE,
    total_amount NUMBER
SELECT order_id, order_date,total_amount, customer_name FROM Orders o JOIN Customers c USING (customer_id);

-- ----------------------------------------------------------------------------------------
-- Write a query to retrieve product names and supplier names from the products and suppliers tables using the USING clause on supplier_id.

DROP TABLE Products;
DROP TABLE Suppliers;

-- Create Suppliers table
CREATE TABLE Suppliers (
                           supplier_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           supplier_name VARCHAR2(100) NOT NULL,
                           phone VARCHAR2(20),
                           city VARCHAR2(100),

                           CONSTRAINT PK_SUPPLIERS PRIMARY KEY (supplier_id)
);

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          price NUMBER,
                          quantity NUMBER,
                          supplier_id NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id),
                          CONSTRAINT FK_PRODUCT_SUPPLIER
                              FOREIGN KEY (supplier_id)
                                  REFERENCES Suppliers(supplier_id)
);

-- Insert sample suppliers
INSERT INTO Suppliers (supplier_name, phone, city)
VALUES ('Dell', '01011111111', 'Cairo');

INSERT INTO Suppliers (supplier_name, phone, city)
VALUES ('HP', '01022222222', 'Alexandria');

INSERT INTO Suppliers (supplier_name, phone, city)
VALUES ('Lenovo', '01033333333', 'Giza');

INSERT INTO Suppliers (supplier_name, phone, city)
VALUES ('Samsung', '01044444444', 'Assiut');

INSERT INTO Suppliers (supplier_name, phone, city)
VALUES ('Logitech', '01055555555', 'Mansoura');

-- Insert sample products
INSERT INTO Products (product_name, price, quantity, supplier_id)
VALUES ('Laptop', 25000, 10, 1);

INSERT INTO Products (product_name, price, quantity, supplier_id)
VALUES ('Printer', 4500, 15, 2);

INSERT INTO Products (product_name, price, quantity, supplier_id)
VALUES ('Desktop', 18000, 8, 3);

INSERT INTO Products (product_name, price, quantity, supplier_id)
VALUES ('Monitor', 6000, 20, 4);

INSERT INTO Products (product_name, price, quantity, supplier_id)
VALUES ('Keyboard', 900, 50, 5);

INSERT INTO Products (product_name, price, quantity, supplier_id)
VALUES ('Mouse', 500, 75, 5);

INSERT INTO Products (product_name, price, quantity, supplier_id)
VALUES ('SSD 1TB', 4200, 25, 3);

-- View data using the USING
SELECT product_name,
       price,
       quantity,
       supplier_name,
       city
FROM Products JOIN Suppliers USING (supplier_id);

-- ----------------------------------------------------------------------------------------
-- Write a query to show student names and course titles by joining students and enrollments using the USING clause on student_id.

DROP TABLE Enrollments;
DROP TABLE Students;

-- Create Students table
CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          student_name VARCHAR2(100) NOT NULL,
                          age NUMBER,
                          city VARCHAR2(100),

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id)
);

-- Create Enrollments table
CREATE TABLE Enrollments (
                             enrollment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             course_name VARCHAR2(100) NOT NULL,
                             semester VARCHAR2(30),
                             student_id NUMBER NOT NULL,

                             CONSTRAINT PK_ENROLLMENTS PRIMARY KEY (enrollment_id),
                             CONSTRAINT FK_ENROLLMENT_STUDENT
                                 FOREIGN KEY (student_id)
                                     REFERENCES Students(student_id)
);

-- Insert sample students
INSERT INTO Students (student_name, age, city)
VALUES ('Mostafa', 22, 'Cairo');

INSERT INTO Students (student_name, age, city)
VALUES ('Ahmed', 21, 'Alexandria');

INSERT INTO Students (student_name, age, city)
VALUES ('Sara', 20, 'Assiut');

INSERT INTO Students (student_name, age, city)
VALUES ('Mona', 23, 'Giza');

INSERT INTO Students (student_name, age, city)
VALUES ('Ali', 24, 'Mansoura');

-- Insert sample enrollments
INSERT INTO Enrollments (course_name, semester, student_id)
VALUES ('Database', 'Fall 2026', 1);

INSERT INTO Enrollments (course_name, semester, student_id)
VALUES ('Java Programming', 'Fall 2026', 2);

INSERT INTO Enrollments (course_name, semester, student_id)
VALUES ('Operating Systems', 'Spring 2027', 3);

INSERT INTO Enrollments (course_name, semester, student_id)
VALUES ('Computer Networks', 'Spring 2027', 4);

INSERT INTO Enrollments (course_name, semester, student_id)
VALUES ('Data Structures', 'Fall 2026', 5);

INSERT INTO Enrollments (course_name, semester, student_id)
VALUES ('Software Engineering', 'Spring 2027', 1);

INSERT INTO Enrollments (course_name, semester, student_id)
VALUES ('Web Development', 'Fall 2026', 3);

-- View data using the USING
SELECT student_name,
       course_name,
       semester
FROM Students
         JOIN Enrollments USING(student_id);

-- -----------------------------------------------------------------------------------------------------------------------
-- Write a query to display invoice numbers and product names by joining invoices and products using the USING clause on product_id.

DROP TABLE Invoices;
DROP TABLE Products;

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          price NUMBER,
                          stock_quantity NUMBER,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-- Create Invoices table
CREATE TABLE Invoices (
                          invoice_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          invoice_date DATE DEFAULT SYSDATE,
                          quantity NUMBER,
                          total_amount NUMBER,
                          product_id NUMBER NOT NULL,

                          CONSTRAINT PK_INVOICES PRIMARY KEY (invoice_id),
                          CONSTRAINT FK_INVOICE_PRODUCT
                              FOREIGN KEY (product_id)
                                  REFERENCES Products(product_id)
);

-- Insert sample products
INSERT INTO Products (product_name, price, stock_quantity)
VALUES ('Laptop', 25000, 10);

INSERT INTO Products (product_name, price, stock_quantity)
VALUES ('Mouse', 500, 100);

INSERT INTO Products (product_name, price, stock_quantity)
VALUES ('Keyboard', 900, 75);

INSERT INTO Products (product_name, price, stock_quantity)
VALUES ('Monitor', 6000, 20);

INSERT INTO Products (product_name, price, stock_quantity)
VALUES ('Printer', 4500, 15);

-- Insert sample invoices
INSERT INTO Invoices (invoice_date, quantity, total_amount, product_id)
VALUES (DATE '2026-07-01', 2, 50000, 1);

INSERT INTO Invoices (invoice_date, quantity, total_amount, product_id)
VALUES (DATE '2026-07-02', 5, 2500, 2);

INSERT INTO Invoices (invoice_date, quantity, total_amount, product_id)
VALUES (DATE '2026-07-03', 3, 2700, 3);

INSERT INTO Invoices (invoice_date, quantity, total_amount, product_id)
VALUES (DATE '2026-07-04', 2, 12000, 4);

INSERT INTO Invoices (invoice_date, quantity, total_amount, product_id)
VALUES (DATE '2026-07-05', 1, 4500, 5);

INSERT INTO Invoices (invoice_date, quantity, total_amount, product_id)
VALUES (DATE '2026-07-06', 1, 25000, 1);

INSERT INTO Invoices (invoice_date, quantity, total_amount, product_id)
VALUES (DATE '2026-07-07', 10, 5000, 2);

-- View data using the USING
SELECT invoice_id,
       invoice_date,
       product_name,
       quantity,
       total_amount
FROM Invoices
         JOIN Products USING (product_id);

-- -----------------------------------------------------------------------------------------------------------------------
-- Write a query to list project names and employee names using the USING clause on project_id.

DROP TABLE Employees;
DROP TABLE Projects;

-- Create Projects table
CREATE TABLE Projects (
                          project_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          project_name VARCHAR2(100) NOT NULL,
                          budget NUMBER,
                          start_date DATE,

                          CONSTRAINT PK_PROJECTS PRIMARY KEY (project_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           project_id NUMBER NOT NULL,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),
                           CONSTRAINT FK_EMPLOYEE_PROJECT
                               FOREIGN KEY (project_id)
                                   REFERENCES Projects(project_id)
);

-- Insert sample projects
INSERT INTO Projects (project_name, budget, start_date)
VALUES ('Inventory System', 50000, DATE '2026-01-10');

INSERT INTO Projects (project_name, budget, start_date)
VALUES ('E-Commerce Website', 120000, DATE '2026-02-15');

INSERT INTO Projects (project_name, budget, start_date)
VALUES ('Banking Application', 250000, DATE '2026-03-20');

INSERT INTO Projects (project_name, budget, start_date)
VALUES ('Hospital Management System', 180000, DATE '2026-04-05');

INSERT INTO Projects (project_name, budget, start_date)
VALUES ('School Management System', 90000, DATE '2026-05-12');

-- Insert sample employees
INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Mostafa', 12000, 1);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Ahmed', 10000, 2);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Sara', 11000, 3);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Mona', 9500, 4);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Ali', 10500, 5);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Omar', 9800, 2);

INSERT INTO Employees (employee_name, salary, project_id)
VALUES ('Nada', 13000, 1);

-- View data using the USING
SELECT employee_name,
       salary,
       project_name,
       budget,
       start_date
FROM Employees
         JOIN Projects USING (project_id);

-- -----------------------------------------------------------------------------------------------------------------------
-- Write a query to retrieve author names and book titles using the USING clause on author_id.


DROP TABLE Books;
DROP TABLE Authors;

-- Create Authors table
CREATE TABLE Authors (
                         author_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         author_name VARCHAR2(100) NOT NULL,
                         country VARCHAR2(100),

                         CONSTRAINT PK_AUTHORS PRIMARY KEY (author_id)
);

-- Create Books table
CREATE TABLE Books (
                       book_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       book_title VARCHAR2(150) NOT NULL,
                       publish_year NUMBER,
                       price NUMBER,
                       author_id NUMBER NOT NULL,

                       CONSTRAINT PK_BOOKS PRIMARY KEY (book_id),
                       CONSTRAINT FK_BOOK_AUTHOR
                           FOREIGN KEY (author_id)
                               REFERENCES Authors(author_id)
);

-- Insert sample authors
INSERT INTO Authors (author_name, country)
VALUES ('Naguib Mahfouz', 'Egypt');

INSERT INTO Authors (author_name, country)
VALUES ('Ahmed Khaled Tawfik', 'Egypt');

INSERT INTO Authors (author_name, country)
VALUES ('Paulo Coelho', 'Brazil');

INSERT INTO Authors (author_name, country)
VALUES ('J. K. Rowling', 'United Kingdom');

INSERT INTO Authors (author_name, country)
VALUES ('George Orwell', 'United Kingdom');

-- Insert sample books
INSERT INTO Books (book_title, publish_year, price, author_id)
VALUES ('Palace Walk', 1956, 180, 1);

INSERT INTO Books (book_title, publish_year, price, author_id)
VALUES ('Utopia', 2008, 150, 2);

INSERT INTO Books (book_title, publish_year, price, author_id)
VALUES ('The Alchemist', 1988, 220, 3);

INSERT INTO Books (book_title, publish_year, price, author_id)
VALUES ('Harry Potter and the Philosopher''s Stone', 1997, 350, 4);

INSERT INTO Books (book_title, publish_year, price, author_id)
VALUES ('1984', 1949, 200, 5);

INSERT INTO Books (book_title, publish_year, price, author_id)
VALUES ('Animal Farm', 1945, 170, 5);

INSERT INTO Books (book_title, publish_year, price, author_id)
VALUES ('Harry Potter and the Chamber of Secrets', 1998, 370, 4);

-- View data using the USING
SELECT book_title,
       publish_year,
       price,
       author_name,
       country
FROM Books
         JOIN Authors USING (author_id);

-- -----------------------------------------------------------------------------------------------------------------------
-- Write a query to show sales order details with employee names using the USING clause on employee_id.

DROP TABLE Order_Details;
DROP TABLE Employees;

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           employee_name VARCHAR2(100) NOT NULL,
                           department VARCHAR2(100),
                           salary NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id)
);

-- Create Order_Details table
CREATE TABLE Order_Details (
                               order_detail_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                               product_name VARCHAR2(100) NOT NULL,
                               quantity NUMBER,
                               unit_price NUMBER,
                               employee_id NUMBER NOT NULL,

                               CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY (order_detail_id),
                               CONSTRAINT FK_ORDERDETAIL_EMPLOYEE
                                   FOREIGN KEY (employee_id)
                                       REFERENCES Employees(employee_id)
);

-- Insert sample employees
INSERT INTO Employees (employee_name, department, salary)
VALUES ('Mostafa', 'Sales', 12000);

INSERT INTO Employees (employee_name, department, salary)
VALUES ('Ahmed', 'Sales', 10000);

INSERT INTO Employees (employee_name, department, salary)
VALUES ('Sara', 'Marketing', 11000);

INSERT INTO Employees (employee_name, department, salary)
VALUES ('Mona', 'IT', 13000);

INSERT INTO Employees (employee_name, department, salary)
VALUES ('Ali', 'HR', 9000);

-- Insert sample order details
INSERT INTO Order_Details (product_name, quantity, unit_price, employee_id)
VALUES ('Laptop', 2, 25000, 1);

INSERT INTO Order_Details (product_name, quantity, unit_price, employee_id)
VALUES ('Mouse', 5, 500, 2);

INSERT INTO Order_Details (product_name, quantity, unit_price, employee_id)
VALUES ('Keyboard', 3, 900, 3);

INSERT INTO Order_Details (product_name, quantity, unit_price, employee_id)
VALUES ('Monitor', 1, 6000, 4);

INSERT INTO Order_Details (product_name, quantity, unit_price, employee_id)
VALUES ('Printer', 2, 4500, 5);

INSERT INTO Order_Details (product_name, quantity, unit_price, employee_id)
VALUES ('SSD', 4, 3500, 1);

INSERT INTO Order_Details (product_name, quantity, unit_price, employee_id)
VALUES ('Headset', 6, 1200, 2);

-- View data using the USING
SELECT employee_name,
       department,
       product_name,
       quantity,
       unit_price
FROM Employees
         JOIN Order_Details USING (employee_id);

-- -----------------------------------------------------------------------------------------------------------------------
-- Write a query to display course schedules and instructor names using the USING clause on instructor_id.

DROP TABLE Course_Schedules;
DROP TABLE Instructors;

-- Create Instructors table
CREATE TABLE Instructors (
                             instructor_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             instructor_name VARCHAR2(100) NOT NULL,
                             specialization VARCHAR2(100),

                             CONSTRAINT PK_INSTRUCTORS PRIMARY KEY (instructor_id)
);

-- Create Course Schedules table
CREATE TABLE Course_Schedules (
                                  schedule_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                                  course_name VARCHAR2(100) NOT NULL,
                                  day_of_week VARCHAR2(20),
                                  class_time VARCHAR2(20),
                                  room_number VARCHAR2(20),
                                  instructor_id NUMBER NOT NULL,

                                  CONSTRAINT PK_COURSE_SCHEDULES PRIMARY KEY (schedule_id),
                                  CONSTRAINT FK_SCHEDULE_INSTRUCTOR
                                      FOREIGN KEY (instructor_id)
                                          REFERENCES Instructors(instructor_id)
);

-- Insert sample instructors
INSERT INTO Instructors (instructor_name, specialization)
VALUES ('Mostafa', 'Database');

INSERT INTO Instructors (instructor_name, specialization)
VALUES ('Ahmed', 'Java');

INSERT INTO Instructors (instructor_name, specialization)
VALUES ('Sara', 'Networking');

INSERT INTO Instructors (instructor_name, specialization)
VALUES ('Mona', 'Operating Systems');

INSERT INTO Instructors (instructor_name, specialization)
VALUES ('Ali', 'Web Development');

-- Insert sample course schedules
INSERT INTO Course_Schedules (course_name, day_of_week, class_time, room_number, instructor_id)
VALUES ('Oracle SQL', 'Sunday', '09:00 AM', 'Lab 1', 1);

INSERT INTO Course_Schedules (course_name, day_of_week, class_time, room_number, instructor_id)
VALUES ('Java Programming', 'Monday', '11:00 AM', 'Lab 2', 2);

INSERT INTO Course_Schedules (course_name, day_of_week, class_time, room_number, instructor_id)
VALUES ('Computer Networks', 'Tuesday', '01:00 PM', 'Lab 3', 3);

INSERT INTO Course_Schedules (course_name, day_of_week, class_time, room_number, instructor_id)
VALUES ('Operating Systems', 'Wednesday', '10:00 AM', 'Lab 4', 4);

INSERT INTO Course_Schedules (course_name, day_of_week, class_time, room_number, instructor_id)
VALUES ('Web Development', 'Thursday', '02:00 PM', 'Lab 5', 5);

INSERT INTO Course_Schedules (course_name, day_of_week, class_time, room_number, instructor_id)
VALUES ('PL/SQL', 'Saturday', '12:00 PM', 'Lab 1', 1);

INSERT INTO Course_Schedules (course_name, day_of_week, class_time, room_number, instructor_id)
VALUES ('Advanced Java', 'Sunday', '03:00 PM', 'Lab 2', 2);

-- View data using the USING
SELECT course_name,
       day_of_week,
       class_time,
       room_number,
       instructor_name,
       specialization
FROM Course_Schedules
         JOIN Instructors USING (instructor_id);

-- -----------------------------------------------------------------------------------------------------------------------
-- Write a query to list transactions along with account holder names using the USING clause on account_id.

DROP TABLE Transactions;
DROP TABLE Accounts;

-- Create Accounts table
CREATE TABLE Accounts (
                          account_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          account_holder VARCHAR2(100) NOT NULL,
                          account_type VARCHAR2(50),
                          balance NUMBER,

                          CONSTRAINT PK_ACCOUNTS PRIMARY KEY (account_id)
);

-- Create Transactions table
CREATE TABLE Transactions (
                              transaction_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                              transaction_date DATE DEFAULT SYSDATE,
                              transaction_type VARCHAR2(20),
                              amount NUMBER,
                              account_id NUMBER NOT NULL,

                              CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (transaction_id),
                              CONSTRAINT FK_TRANSACTION_ACCOUNT
                                  FOREIGN KEY (account_id)
                                      REFERENCES Accounts(account_id)
);

-- Insert sample accounts
INSERT INTO Accounts (account_holder, account_type, balance)
VALUES ('Mostafa', 'Savings', 15000);

INSERT INTO Accounts (account_holder, account_type, balance)
VALUES ('Ahmed', 'Current', 8500);

INSERT INTO Accounts (account_holder, account_type, balance)
VALUES ('Sara', 'Savings', 12000);

INSERT INTO Accounts (account_holder, account_type, balance)
VALUES ('Mona', 'Current', 20000);

INSERT INTO Accounts (account_holder, account_type, balance)
VALUES ('Ali', 'Savings', 9500);

-- Insert sample transactions
INSERT INTO Transactions (transaction_type, amount, account_id)
VALUES ('Deposit', 5000, 1);

INSERT INTO Transactions (transaction_type, amount, account_id)
VALUES ('Withdraw', 1000, 1);

INSERT INTO Transactions (transaction_type, amount, account_id)
VALUES ('Deposit', 3000, 2);

INSERT INTO Transactions (transaction_type, amount, account_id)
VALUES ('Withdraw', 2000, 3);

INSERT INTO Transactions (transaction_type, amount, account_id)
VALUES ('Deposit', 7000, 4);

INSERT INTO Transactions (transaction_type, amount, account_id)
VALUES ('Withdraw', 500, 5);

INSERT INTO Transactions (transaction_type, amount, account_id)
VALUES ('Deposit', 2500, 2);

-- View data using the USING
SELECT account_holder,
       account_type,
       balance,
       transaction_type,
       amount,
       transaction_date
FROM Accounts
         JOIN Transactions USING (account_id);






































