-- Write a query to retrieve employee names and their manager names from the employees table, handling ambiguous column names for employee_id and manager_id.

DROP TABLE Employees;
DROP TABLE Managers;

-- Create Managers table
CREATE TABLE Managers (
                          manager_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          name VARCHAR2(100) NOT NULL,
                          department VARCHAR2(100),

                          CONSTRAINT PK_MANAGERS PRIMARY KEY (manager_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           manager_id NUMBER NOT NULL,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),
                           CONSTRAINT FK_EMPLOYEE_MANAGER
                               FOREIGN KEY (manager_id)
                                   REFERENCES Managers(manager_id)
);

-- Insert sample managers
INSERT INTO Managers (name, department)
VALUES ('Mohamed Hassan', 'IT');

INSERT INTO Managers (name, department)
VALUES ('Ahmed Ali', 'HR');

INSERT INTO Managers (name, department)
VALUES ('Sara Mahmoud', 'Finance');

INSERT INTO Managers (name, department)
VALUES ('Mona Ibrahim', 'Marketing');

INSERT INTO Managers (name, department)
VALUES ('Omar Adel', 'Sales');

-- Insert sample employees
INSERT INTO Employees (name, salary, manager_id)
VALUES ('Mostafa', 12000, 1);

INSERT INTO Employees (name, salary, manager_id)
VALUES ('Ali', 9500, 1);

INSERT INTO Employees (name, salary, manager_id)
VALUES ('Youssef', 8500, 2);

INSERT INTO Employees (name, salary, manager_id)
VALUES ('Nada', 11000, 3);

INSERT INTO Employees (name, salary, manager_id)
VALUES ('Hana', 10000, 4);

INSERT INTO Employees (name, salary, manager_id)
VALUES ('Karim', 9000, 5);

INSERT INTO Employees (name, salary, manager_id)
VALUES ('Mariam', 10500, 3);

-- View data using NATURAL JOIN
SELECT e.name AS Employee_Name,
       m.name AS Manager_Name
FROM Employees  e
         JOIN Managers m
              ON  e.manager_id = m.manager_id;
-- ---------------------------------------------------------------------------------------------------------
-- Write a query to list customer names and salesperson names from the customers and employees tables, where both tables have a column named name.

DROP TABLE Customers;
DROP TABLE Employees;

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           name VARCHAR2(100) NOT NULL,
                           department VARCHAR2(100),

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id)
);

-- Create Customers table
CREATE TABLE Customers (
                           customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           name VARCHAR2(100) NOT NULL,
                           city VARCHAR2(100),
                           salesperson_id NUMBER,

                           CONSTRAINT PK_CUSTOMERS PRIMARY KEY (customer_id),
                           CONSTRAINT FK_CUSTOMER_EMPLOYEE
                               FOREIGN KEY (salesperson_id)
                                   REFERENCES Employees(employee_id)
);

-- Insert employees
INSERT INTO Employees (name, department)
VALUES ('Mostafa', 'Sales');

INSERT INTO Employees (name, department)
VALUES ('Ahmed', 'Sales');

INSERT INTO Employees (name, department)
VALUES ('Sara', 'Sales');

-- Insert customers
INSERT INTO Customers (name, city, salesperson_id)
VALUES ('Ali', 'Cairo', 1);

INSERT INTO Customers (name, city, salesperson_id)
VALUES ('Omar', 'Alexandria', 2);

INSERT INTO Customers (name, city, salesperson_id)
VALUES ('Hassan', 'Assiut', 1);

INSERT INTO Customers (name, city, salesperson_id)
VALUES ('Mona', 'Giza', 3);

-- Query
SELECT c.name AS Customer_Name, e.name AS Employee_Name
FROM CUSTOMERS c
         JOIN EMPLOYEES e
              ON c.SALESPERSON_ID  = e.EMPLOYEE_ID ;

-- ---------------------------------------------------------------------------------------------------------
-- Write a query to display order IDs and product IDs from orders and order_details, both of which have an order_id column.

DROP TABLE Order_Details;
DROP TABLE Orders;
DROP TABLE Products;

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          product_name VARCHAR2(100) NOT NULL,
                          price NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id)
);

-- Create Orders table
CREATE TABLE Orders (
                        order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        customer_name VARCHAR2(100) NOT NULL,
                        order_date DATE,
                        status VARCHAR2(20),

                        CONSTRAINT PK_ORDERS PRIMARY KEY (order_id)
);

-- Create Order_Details table
CREATE TABLE Order_Details (
                               detail_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                               order_id NUMBER NOT NULL,
                               product_id NUMBER NOT NULL,
                               quantity NUMBER,
                               unit_price NUMBER,

                               CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY (detail_id),

                               CONSTRAINT FK_ORDER_DETAILS_ORDER
                                   FOREIGN KEY (order_id)
                                       REFERENCES Orders(order_id),

                               CONSTRAINT FK_ORDER_DETAILS_PRODUCT
                                   FOREIGN KEY (product_id)
                                       REFERENCES Products(product_id)
);

-- Insert sample products
INSERT INTO Products (product_name, price)
VALUES ('Laptop', 25000);

INSERT INTO Products (product_name, price)
VALUES ('Mouse', 500);

INSERT INTO Products (product_name, price)
VALUES ('Keyboard', 1200);

INSERT INTO Products (product_name, price)
VALUES ('Monitor', 6000);

INSERT INTO Products (product_name, price)
VALUES ('Printer', 4500);

INSERT INTO Products (product_name, price)
VALUES ('USB Flash', 350);

INSERT INTO Products (product_name, price)
VALUES ('Headset', 1800);

-- Insert sample orders
INSERT INTO Orders (customer_name, order_date, status)
VALUES ('Ali', DATE '2026-07-20', 'Completed');

INSERT INTO Orders (customer_name, order_date, status)
VALUES ('Omar', DATE '2026-07-21', 'Pending');

INSERT INTO Orders (customer_name, order_date, status)
VALUES ('Sara', DATE '2026-07-22', 'Completed');

INSERT INTO Orders (customer_name, order_date, status)
VALUES ('Mona', DATE '2026-07-23', 'Cancelled');

-- Insert sample order details
INSERT INTO Order_Details (order_id, product_id, quantity, unit_price)
VALUES (1, 1, 1, 25000);

INSERT INTO Order_Details (order_id, product_id, quantity, unit_price)
VALUES (1, 2, 2, 500);

INSERT INTO Order_Details (order_id, product_id, quantity, unit_price)
VALUES (2, 3, 1, 1200);

INSERT INTO Order_Details (order_id, product_id, quantity, unit_price)
VALUES (2, 4, 2, 6000);

INSERT INTO Order_Details (order_id, product_id, quantity, unit_price)
VALUES (3, 5, 1, 4500);

INSERT INTO Order_Details (order_id, product_id, quantity, unit_price)
VALUES (3, 6, 3, 350);

INSERT INTO Order_Details (order_id, product_id, quantity, unit_price)
VALUES (4, 7, 1, 1800);


SELECT o.order_id, od.product_id
FROM Orders o
         JOIN Order_Details od
              ON o.order_id = od.order_id;

-- ---------------------------------------------------------------------------------------------------------
-- Write a query to retrieve student names and instructor names from students and instructors tables using an alias to handle the name column.

DROP TABLE Students;
DROP TABLE Instructors;

-- Create Instructors table
CREATE TABLE Instructors (
                             instructor_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             name VARCHAR2(100) NOT NULL,
                             department VARCHAR2(100),

                             CONSTRAINT PK_INSTRUCTORS PRIMARY KEY (instructor_id)
);

-- Create Students table
CREATE TABLE Students (
                          student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          name VARCHAR2(100) NOT NULL,
                          age NUMBER,
                          instructor_id NUMBER NOT NULL,

                          CONSTRAINT PK_STUDENTS PRIMARY KEY (student_id),

                          CONSTRAINT FK_STUDENT_INSTRUCTOR
                              FOREIGN KEY (instructor_id)
                                  REFERENCES Instructors(instructor_id)
);

-- Insert sample instructors
INSERT INTO Instructors (name, department)
VALUES ('Dr. Ahmed Hassan', 'Computer Science');

INSERT INTO Instructors (name, department)
VALUES ('Dr. Sara Ali', 'Information Systems');

INSERT INTO Instructors (name, department)
VALUES ('Dr. Mohamed Salah', 'Software Engineering');

INSERT INTO Instructors (name, department)
VALUES ('Dr. Mona Ibrahim', 'Artificial Intelligence');

-- Insert sample students
INSERT INTO Students (name, age, instructor_id)
VALUES ('Mostafa', 22, 1);

INSERT INTO Students (name, age, instructor_id)
VALUES ('Ali', 21, 1);

INSERT INTO Students (name, age, instructor_id)
VALUES ('Omar', 23, 2);

INSERT INTO Students (name, age, instructor_id)
VALUES ('Sara', 20, 3);

INSERT INTO Students (name, age, instructor_id)
VALUES ('Mona', 22, 4);

INSERT INTO Students (name, age, instructor_id)
VALUES ('Youssef', 21, 2);

INSERT INTO Students (name, age, instructor_id)
VALUES ('Hana', 20, 3);

SELECT s.name AS Student_Name, i.name AS Instructor_Name
FROM Students s
         JOIN Instructors i
              ON s.instructor_id = i.instructor_id;

-- ---------------------------------------------------------------------------------------------------------
-- Write a query to show employee salaries and department budgets, both of which have a budget or salary column that could conflict.

DROP TABLE Departments;
DROP TABLE Employees;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             name VARCHAR2(100) NOT NULL,
                             salary NUMBER,

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           name VARCHAR2(100) NOT NULL,
                           salary NUMBER,
                           department_id NUMBER,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),
                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);



-------------------------------------------------
-- Insert Departments
-------------------------------------------------

INSERT INTO Departments (name, salary)
VALUES ('IT', 500000);

INSERT INTO Departments (name, salary)
VALUES ('HR', 200000);

INSERT INTO Departments (name, salary)
VALUES ('Finance', 350000);

INSERT INTO Departments (name, salary)
VALUES ('Marketing', 250000);

-------------------------------------------------
-- Insert Employees
-------------------------------------------------

INSERT INTO Employees (name, salary, department_id)
VALUES ('Mostafa', 18000, 1);

INSERT INTO Employees (name, salary, department_id)
VALUES ('Ahmed', 15000, 1);

INSERT INTO Employees (name, salary, department_id)
VALUES ('Sara', 12000, 2);

INSERT INTO Employees (name, salary, department_id)
VALUES ('Mona', 22000, 3);

INSERT INTO Employees (name, salary, department_id)
VALUES ('Ali', 14000, 4);

INSERT INTO Employees (name, salary, department_id)
VALUES ('Omar', 25000, 3);


SELECT e.name AS Employee_Name,
       e.salary AS Employee_Salary,
       d.name AS Department_Name,
       d.salary AS Department_Budget
FROM Employees e
         JOIN Departments d
              ON e.department_id = d.department_id;

-- ---------------------------------------------------------------------------------------------------------
-- Write a query to display project names and task names where both projects and tasks tables contain a name column.

DROP TABLE Tasks;
DROP TABLE Projects;

-- Create Projects table
CREATE TABLE Projects (
                          project_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          name VARCHAR2(100) NOT NULL,
                          start_date DATE,

                          CONSTRAINT PK_PROJECTS PRIMARY KEY (project_id)
);

-- Create Tasks table
CREATE TABLE Tasks (
                       task_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       name VARCHAR2(100) NOT NULL,
                       status VARCHAR2(20),
                       project_id NUMBER NOT NULL,

                       CONSTRAINT PK_TASKS PRIMARY KEY (task_id),

                       CONSTRAINT FK_TASK_PROJECT
                           FOREIGN KEY (project_id)
                               REFERENCES Projects(project_id)
);

-------------------------------------------------
-- Insert sample projects
-------------------------------------------------

INSERT INTO Projects (name, start_date)
VALUES ('Inventory System', DATE '2026-07-01');

INSERT INTO Projects (name, start_date)
VALUES ('E-Commerce Website', DATE '2026-07-05');

INSERT INTO Projects (name, start_date)
VALUES ('Hospital Management', DATE '2026-07-10');

-------------------------------------------------
-- Insert sample tasks
-------------------------------------------------

INSERT INTO Tasks (name, status, project_id)
VALUES ('Design Database', 'Completed', 1);

INSERT INTO Tasks (name, status, project_id)
VALUES ('Build APIs', 'In Progress', 1);

INSERT INTO Tasks (name, status, project_id)
VALUES ('Create Home Page', 'Completed', 2);

INSERT INTO Tasks (name, status, project_id)
VALUES ('Implement Payment', 'Pending', 2);

INSERT INTO Tasks (name, status, project_id)
VALUES ('Patient Registration', 'Completed', 3);

INSERT INTO Tasks (name, status, project_id)
VALUES ('Medical Reports', 'Pending', 3);


SELECT p.name AS Project_Name,
       t.name AS Task_Name
FROM Projects p
         JOIN Tasks t
              ON p.project_id = t.project_id;

-- ---------------------------------------------------------------------------------------------------------
-- Write a query to join courses and exams tables and retrieve their date fields, resolving ambiguity between the columns.

DROP TABLE Exams;
DROP TABLE Courses;

-- Create Courses table
CREATE TABLE Courses (
                         course_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         course_name VARCHAR2(100) NOT NULL,
                         time_date DATE,

                         CONSTRAINT PK_COURSES PRIMARY KEY (course_id)
);

-- Create Exams table
CREATE TABLE Exams (
                       exam_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       exam_name VARCHAR2(100) NOT NULL,
                       time_date DATE,
                       total_marks NUMBER,
                       course_id NUMBER NOT NULL,

                       CONSTRAINT PK_EXAMS PRIMARY KEY (exam_id),

                       CONSTRAINT FK_EXAM_COURSE
                           FOREIGN KEY (course_id)
                               REFERENCES Courses(course_id)
);

-------------------------------------------------
-- Insert sample courses
-------------------------------------------------

INSERT INTO Courses (course_name, time_date)
VALUES ('Database Systems', DATE '2026-08-01');

INSERT INTO Courses (course_name, time_date)
VALUES ('Data Structures', DATE '2026-08-03');

INSERT INTO Courses (course_name, time_date)
VALUES ('Operating Systems', DATE '2026-08-05');

INSERT INTO Courses (course_name, time_date)
VALUES ('Software Engineering', DATE '2026-08-07');

-------------------------------------------------
-- Insert sample exams
-------------------------------------------------

INSERT INTO Exams (exam_name, time_date, total_marks, course_id)
VALUES ('Midterm', DATE '2026-09-10', 30, 1);

INSERT INTO Exams (exam_name, time_date, total_marks, course_id)
VALUES ('Final', DATE '2026-10-15', 70, 1);

INSERT INTO Exams (exam_name, time_date, total_marks, course_id)
VALUES ('Midterm', DATE '2026-09-12', 30, 2);

INSERT INTO Exams (exam_name, time_date, total_marks, course_id)
VALUES ('Final', DATE '2026-10-18', 70, 2);

INSERT INTO Exams (exam_name, time_date, total_marks, course_id)
VALUES ('Final', DATE '2026-10-20', 100, 3);

INSERT INTO Exams (exam_name, time_date, total_marks, course_id)
VALUES ('Practical', DATE '2026-09-25', 40, 4);

INSERT INTO Exams (exam_name, time_date, total_marks, course_id)
VALUES ('Final', DATE '2026-10-22', 60, 4);

SELECT
    c.course_name,
    c.time_date AS course_date,
    e.exam_name,
    e.time_date AS exam_date,
    e.total_marks
FROM Courses c
         JOIN Exams e
              ON c.course_id = e.course_id;

-- ---------------------------------------------------------------------------------------------------------
-- Write a query to show the product name and category name from the products and categories tables, where both have a name column.

DROP TABLE Products;
DROP TABLE Categories;

-- Create Categories table
CREATE TABLE Categories (
                            category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            name VARCHAR2(100) NOT NULL,

                            CONSTRAINT PK_CATEGORIES PRIMARY KEY (category_id)
);

-- Create Products table
CREATE TABLE Products (
                          product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          name VARCHAR2(100) NOT NULL,
                          price NUMBER,
                          category_id NUMBER NOT NULL,

                          CONSTRAINT PK_PRODUCTS PRIMARY KEY (product_id),

                          CONSTRAINT FK_PRODUCT_CATEGORY
                              FOREIGN KEY (category_id)
                                  REFERENCES Categories(category_id)
);

-------------------------------------------------
-- Insert sample categories
-------------------------------------------------

INSERT INTO Categories (name)
VALUES ('Electronics');

INSERT INTO Categories (name)
VALUES ('Furniture');

INSERT INTO Categories (name)
VALUES ('Accessories');

INSERT INTO Categories (name)
VALUES ('Appliances');

-------------------------------------------------
-- Insert sample products
-------------------------------------------------

INSERT INTO Products (name, price, category_id)
VALUES ('Laptop', 25000, 1);

INSERT INTO Products (name, price, category_id)
VALUES ('Mouse', 500, 1);

INSERT INTO Products (name, price, category_id)
VALUES ('Office Chair', 3500, 2);

INSERT INTO Products (name, price, category_id)
VALUES ('USB Flash', 350, 3);

INSERT INTO Products (name, price, category_id)
VALUES ('Headphones', 1800, 3);

INSERT INTO Products (name, price, category_id)
VALUES ('Refrigerator', 22000, 4);


SELECT p.name AS product_name,
       c.name AS category_name
FROM Products p
         JOIN Categories c
              ON p.category_id = c.category_id;

-- ---------------------------------------------------------------------------------------------------------
-- Write a query to display the book title and publisher name from books and publishers, avoiding column name conflicts.

DROP TABLE Books;
DROP TABLE Publishers;

-- Create Publishers table
CREATE TABLE Publishers (
                            publisher_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            name VARCHAR2(100) NOT NULL,
                            country VARCHAR2(50),

                            CONSTRAINT PK_PUBLISHERS PRIMARY KEY (publisher_id)
);

-- Create Books table
CREATE TABLE Books (
                       book_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       name VARCHAR2(100) NOT NULL,
                       price NUMBER,
                       publisher_id NUMBER NOT NULL,

                       CONSTRAINT PK_BOOKS PRIMARY KEY (book_id),

                       CONSTRAINT FK_BOOK_PUBLISHER
                           FOREIGN KEY (publisher_id)
                               REFERENCES Publishers(publisher_id)
);

-------------------------------------------------
-- Insert sample publishers
-------------------------------------------------

INSERT INTO Publishers (name, country)
VALUES ('O''Reilly Media', 'USA');

INSERT INTO Publishers (name, country)
VALUES ('Pearson', 'UK');

INSERT INTO Publishers (name, country)
VALUES ('McGraw-Hill', 'USA');

INSERT INTO Publishers (name, country)
VALUES ('Springer', 'Germany');

-------------------------------------------------
-- Insert sample books
-------------------------------------------------

INSERT INTO Books (name, price, publisher_id)
VALUES ('Learning SQL', 45, 1);

INSERT INTO Books (name, price, publisher_id)
VALUES ('Java Complete Reference', 60, 3);

INSERT INTO Books (name, price, publisher_id)
VALUES ('Database Systems', 55, 2);

INSERT INTO Books (name, price, publisher_id)
VALUES ('Clean Code', 50, 1);

INSERT INTO Books (name, price, publisher_id)
VALUES ('Algorithms', 65, 4);

INSERT INTO Books (name, price, publisher_id)
VALUES ('Oracle SQL Guide', 58, 2);

SELECT p.name AS Publisher_name,
       b.name AS Book_title
FROM Publishers p
         JOIN Books b
              ON p.publisher_id = b.publisher_id;

-- ---------------------------------------------------------------------------------------------------------
-- Write a query to list employee names and their department's location, resolving ambiguity in the location column from both tables.

DROP TABLE Employees;
DROP TABLE Departments;

-- Create Departments table
CREATE TABLE Departments (
                             department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             name VARCHAR2(100) NOT NULL,
                             location VARCHAR2(100) NOT NULL,

                             CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (department_id)
);

-- Create Employees table
CREATE TABLE Employees (
                           employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           name VARCHAR2(100) NOT NULL,
                           location VARCHAR2(100),
                           salary NUMBER,
                           department_id NUMBER NOT NULL,

                           CONSTRAINT PK_EMPLOYEES PRIMARY KEY (employee_id),

                           CONSTRAINT FK_EMPLOYEE_DEPARTMENT
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(department_id)
);

-------------------------------------------------
-- Insert sample departments
-------------------------------------------------

INSERT INTO Departments (name, location)
VALUES ('IT', 'Cairo');

INSERT INTO Departments (name, location)
VALUES ('HR', 'Alexandria');

INSERT INTO Departments (name, location)
VALUES ('Finance', 'Giza');

INSERT INTO Departments (name, location)
VALUES ('Marketing', 'Assiut');

-------------------------------------------------
-- Insert sample employees
-------------------------------------------------

INSERT INTO Employees (name, location, salary, department_id)
VALUES ('Mostafa', 'Cairo', 18000, 1);

INSERT INTO Employees (name, location, salary, department_id)
VALUES ('Ahmed', 'Cairo', 15000, 1);

INSERT INTO Employees (name, location, salary, department_id)
VALUES ('Sara', 'Alexandria', 12000, 2);

INSERT INTO Employees (name, location, salary, department_id)
VALUES ('Mona', 'Giza', 22000, 3);

INSERT INTO Employees (name, location, salary, department_id)
VALUES ('Ali', 'Assiut', 14000, 4);

INSERT INTO Employees (name, location, salary, department_id)
VALUES ('Omar', 'Giza', 25000, 3);



SELECT
    e.name AS employee_name,
    e.location AS employee_location,
    d.name AS department_name,
    d.location AS department_location,
    e.salary
FROM Employees e
         JOIN Departments d
              ON e.department_id = d.department_id;