-- Drop a CHECK constraint named chk_salary from the Employees table.

CREATE TABLE Employees(
                          id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          salary NUMBER,
                          CONSTRAINT PK_EMPLOYEES PRIMARY KEY(id),
                          CONSTRAINT CHK_SALARY CHECK(salary > 0)
);

-- SQL Error [2290] [23000]: ORA-02290: check constraint (ITEM.CHK_SALARY) violated
INSERT INTO Employees (salary) VALUES (0);

ALTER TABLE Employees DROP CONSTRAINT CHK_SALARY;

-- Updated Rows 1
INSERT INTO Employees (salary) VALUES (0);

-- ---------------------------------------------------------------------------------------------------
-- Remove the UNIQUE constraint on email from the Users table.

CREATE TABLE Users(
                      id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                      email VARCHAR2(200) CONSTRAINT UQ_USERS_EMAIL UNIQUE,
                      CONSTRAINT PK_USERS PRIMARY KEY(id)
);

-- Updated Rows 1
INSERT INTO Users (email)
VALUES ('mostafa@gmail.com');

-- SQL Error [1] [23000]: ORA-00001: unique constraint (ITEM.UQ_USERS_EMAIL) violated
INSERT INTO Users (email)
VALUES ('mostafa@gmail.com');

ALTER TABLE Employees DROP CONSTRAINT UQ_USERS_EMAIL;

-- Updated Rows 1
INSERT INTO Users (email)
VALUES ('mostafa@gmail.com');

-- ---------------------------------------------------------------------------------------------------
-- Drop the PRIMARY KEY from the Products table.

CREATE TABLE Products(
                         id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         CONSTRAINT PK_PRODUCTS PRIMARY KEY(id)
);

-- Updated Rows 1
INSERT INTO Products (id) VALUES (1);

-- SQL Error [1] [23000]: ORA-00001: unique constraint (ITEM.PK_PRODUCTS) violated
INSERT INTO Products (id) VALUES (1);

ALTER TABLE Products DROP CONSTRAINT PK_PRODUCTS;

-- Updated Rows 1
INSERT INTO Products (id) VALUES (1);

-- ---------------------------------------------------------------------------------------------------
-- Drop a FOREIGN KEY constraint named fk_order_customer from the Orders table.

CREATE TABLE Orders(
                       id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       customer_id NUMBER,
                       CONSTRAINT PK_ORDERS PRIMARY KEY(id),
                       CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (customer_id) REFERENCES Customers(id)
);

-- SQL Error [2291] [23000]: ORA-02291: integrity constraint (ITEM.FK_ORDER_CUSTOMER) violated - parent key not found
INSERT INTO Orders (customer_id) VALUES (1000);

ALTER TABLE Orders DROP CONSTRAINT FK_ORDER_CUSTOMER;

-- Updated Rows 1
INSERT INTO Orders (customer_id) VALUES (1000);

-- ---------------------------------------------------------------------------------------------------
-- Write SQL to remove a NOT NULL constraint from the phone column in the Contacts table.

DROP TABLE Contacts;

CREATE TABLE Contacts(
                         id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         phone NUMBER CONSTRAINT NN_PHONE NOT NULL,
                         CONSTRAINT PK_CONTACTS PRIMARY KEY(id)
);

-- SQL Error [1400] [23000]: ORA-01400: cannot insert NULL into ("ITEM"."CONTACTS"."PHONE")
INSERT INTO Contacts (phone) VALUES (NULL);

ALTER TABLE Contacts DROP CONSTRAINT NN_PHONE;

-- Updated Rows 1
INSERT INTO Contacts (phone) VALUES (NULL);

-- ---------------------------------------------------------------------------------------------------